#!/usr/bin/env python3
"""
Complete Arabic Translation Script
Translates ALL remaining English text to Arabic while preserving technical terms.
"""

import json
import re
import os
import sys
from typing import Dict, Any, List, Tuple
from datetime import datetime

class CompleteArabicTranslator:
    def __init__(self):
        # Company/product names to preserve
        self.preserve_exact = {
            'Seasalt.ai', 'SeaChat', 'SeaMeet', 'SeaX', 'SeaHealth', 'SeaVoice',
            'Twilio', 'Meta', 'Facebook', 'WhatsApp', 'Instagram', 'Line',
            'WordPress', 'Shopify', 'Squarespace', 'Wix', 'MailerLite',
            'HubSpot', 'Mailchimp', 'Google', 'Microsoft', 'GitHub',
            'Genesys', 'Aircall', 'RingCentral', 'Five9', 'Zendesk',
            'Salesforce', 'Slack', 'Discord', 'Telegram', 'LinkedIn',
            'Kustomer', 'Dialpad', 'Twilio Flex', 'BigCommerce',
            'Amadeus', 'Sabre', 'Galileo'
        }
        
        # Technical acronyms to preserve
        self.technical_acronyms = {
            'API', 'SDK', 'JSON', 'HTML', 'CSS', 'JavaScript', 'Python',
            'REST', 'GraphQL', 'OAuth', 'SSO', 'SAML', 'IVR', 'PBX',
            'SOC', 'HIPAA', 'GDPR', 'TCPA', 'FINRA', 'PCI', 'DSS',
            '10DLC', 'SMS', 'MMS', 'SIP', 'VoIP', 'WebRTC', 'SMTP',
            'AI', 'ML', 'NLP', 'LLM', 'RAG', 'TTS', 'STT', 'ASR',
            'CRM', 'ERP', 'SaaS', 'PaaS', 'IaaS', 'UCaaS', 'CCaaS',
            'UI', 'UX', 'B2B', 'B2C', 'SEO', 'SEM', 'CTR', 'CPC',
            'CPA', 'ROI', 'KPI', 'ROAS', 'LTV', 'CAC', 'GDS',
            'URL', 'URI', 'HTTP', 'HTTPS', 'FTP', 'DNS', 'IP',
            'ISO', 'SQL', 'CSV', 'XML', 'PDF', 'PNG', 'JPG', 'GIF'
        }
        
        # Comprehensive translation dictionary
        self.translations = {
            # Navigation & UI
            "Products": "المنتجات",
            "Product": "المنتج",
            "Solutions": "الحلول",
            "Solution": "الحل",
            "Industries": "الصناعات",
            "Industry": "الصناعة",
            "Channels": "القنوات",
            "Channel": "القناة",
            "Pricing": "الأسعار",
            "Price": "السعر",
            "Blog": "المدونة",
            "Blogs": "المدونات",
            "Support": "الدعم",
            "Help": "المساعدة",
            "Resources": "الموارد",
            "Resource": "المورد",
            "Documentation": "التوثيق",
            "Docs": "الوثائق",
            "Login": "تسجيل الدخول",
            "Sign In": "تسجيل الدخول",
            "Sign Up": "التسجيل",
            "Register": "التسجيل",
            "Logout": "تسجيل الخروج",
            "Sign Out": "تسجيل الخروج",
            
            # Actions & CTAs
            "Get Started": "ابدأ الآن",
            "Start": "ابدأ",
            "Start Free": "ابدأ مجاناً",
            "Start Now": "ابدأ الآن",
            "Try Free": "جرب مجاناً",
            "Try Now": "جرب الآن",
            "Free Trial": "تجربة مجانية",
            "Book Demo": "احجز عرضاً تجريبياً",
            "Schedule Demo": "احجز عرضاً تجريبياً",
            "See Demo": "شاهد العرض التجريبي",
            "View Demo": "شاهد العرض التجريبي",
            "Watch Demo": "شاهد العرض التجريبي",
            "Contact Us": "اتصل بنا",
            "Contact Sales": "اتصل بالمبيعات",
            "Learn More": "اعرف المزيد",
            "Read More": "اقرأ المزيد",
            "View More": "عرض المزيد",
            "Show More": "أظهر المزيد",
            "See All": "عرض الكل",
            "View All": "عرض الكل",
            "Explore": "استكشف",
            "Discover": "اكتشف",
            "Compare": "قارن",
            "Choose": "اختر",
            "Select": "حدد",
            "Download": "تنزيل",
            "Upload": "تحميل",
            "Save": "حفظ",
            "Submit": "إرسال",
            "Send": "إرسال",
            "Cancel": "إلغاء",
            "Close": "إغلاق",
            "Back": "العودة",
            "Next": "التالي",
            "Previous": "السابق",
            "Home": "الرئيسية",
            "Dashboard": "لوحة التحكم",
            "Settings": "الإعدادات",
            "Profile": "الملف الشخصي",
            "Account": "الحساب",
            
            # Business Terms
            "Business": "الأعمال",
            "Businesses": "الأعمال",
            "Company": "الشركة",
            "Companies": "الشركات",
            "Enterprise": "المؤسسة",
            "Enterprises": "المؤسسات",
            "Organization": "المنظمة",
            "Organizations": "المنظمات",
            "Customer": "العميل",
            "Customers": "العملاء",
            "Client": "العميل",
            "Clients": "العملاء",
            "User": "المستخدم",
            "Users": "المستخدمون",
            "Team": "الفريق",
            "Teams": "الفرق",
            "Agent": "الوكيل",
            "Agents": "الوكلاء",
            "Human Agent": "الوكيل البشري",
            "Human Agents": "الوكلاء البشريون",
            "Live Agent": "الوكيل المباشر",
            "Live Agents": "الوكلاء المباشرون",
            "Staff": "الموظفون",
            "Employee": "الموظف",
            "Employees": "الموظفون",
            "Manager": "المدير",
            "Managers": "المديرون",
            "Supervisor": "المشرف",
            "Supervisors": "المشرفون",
            "Lead": "العميل المحتمل",
            "Leads": "العملاء المحتملون",
            "Prospect": "العميل المحتمل",
            "Prospects": "العملاء المحتملون",
            "Visitor": "الزائر",
            "Visitors": "الزوار",
            "Guest": "الضيف",
            "Guests": "الضيوف",
            
            # Sales & Marketing
            "Sales": "المبيعات",
            "Sale": "البيع",
            "Marketing": "التسويق",
            "Campaign": "الحملة",
            "Campaigns": "الحملات",
            "Advertisement": "الإعلان",
            "Ads": "الإعلانات",
            "Promotion": "الترويج",
            "Promotions": "العروض الترويجية",
            "Offer": "العرض",
            "Offers": "العروض",
            "Deal": "الصفقة",
            "Deals": "الصفقات",
            "Discount": "الخصم",
            "Discounts": "الخصومات",
            "Revenue": "الإيرادات",
            "Income": "الدخل",
            "Profit": "الربح",
            "Growth": "النمو",
            "Conversion": "التحويل",
            "Conversions": "التحويلات",
            "Engagement": "التفاعل",
            "Reach": "الوصول",
            "Target": "الهدف",
            "Targeting": "الاستهداف",
            "Audience": "الجمهور",
            "Segment": "الشريحة",
            "Segments": "الشرائح",
            
            # Communication Terms
            "Communication": "التواصل",
            "Communications": "الاتصالات",
            "Message": "الرسالة",
            "Messages": "الرسائل",
            "Messaging": "المراسلة",
            "Chat": "الدردشة",
            "Chats": "المحادثات",
            "Conversation": "المحادثة",
            "Conversations": "المحادثات",
            "Call": "المكالمة",
            "Calls": "المكالمات",
            "Phone": "الهاتف",
            "Phones": "الهواتف",
            "Voice": "الصوت",
            "Voicemail": "البريد الصوتي",
            "Email": "البريد الإلكتروني",
            "Emails": "رسائل البريد الإلكتروني",
            "Text": "النص",
            "Texts": "النصوص",
            "Notification": "الإشعار",
            "Notifications": "الإشعارات",
            "Alert": "التنبيه",
            "Alerts": "التنبيهات",
            "Update": "التحديث",
            "Updates": "التحديثات",
            "Response": "الرد",
            "Responses": "الردود",
            "Reply": "الرد",
            "Replies": "الردود",
            "Feedback": "التعليقات",
            "Review": "المراجعة",
            "Reviews": "المراجعات",
            
            # Technology Terms
            "Platform": "المنصة",
            "Platforms": "المنصات",
            "System": "النظام",
            "Systems": "الأنظمة",
            "Software": "البرمجيات",
            "Application": "التطبيق",
            "Applications": "التطبيقات",
            "App": "التطبيق",
            "Apps": "التطبيقات",
            "Tool": "الأداة",
            "Tools": "الأدوات",
            "Service": "الخدمة",
            "Services": "الخدمات",
            "Feature": "الميزة",
            "Features": "الميزات",
            "Function": "الوظيفة",
            "Functions": "الوظائف",
            "Capability": "القدرة",
            "Capabilities": "القدرات",
            "Integration": "التكامل",
            "Integrations": "التكاملات",
            "Automation": "الأتمتة",
            "Automated": "مؤتمت",
            "Automatic": "تلقائي",
            "Manual": "يدوي",
            "Custom": "مخصص",
            "Customized": "مخصص",
            "Personalized": "شخصي",
            "Smart": "ذكي",
            "Intelligent": "ذكي",
            "Advanced": "متقدم",
            "Simple": "بسيط",
            "Easy": "سهل",
            "Complex": "معقد",
            "Powerful": "قوي",
            "Robust": "قوي",
            "Secure": "آمن",
            "Safe": "آمن",
            "Protected": "محمي",
            "Encrypted": "مشفر",
            "Private": "خاص",
            "Public": "عام",
            
            # AI & Technology
            "Artificial Intelligence": "الذكاء الاصطناعي",
            "Machine Learning": "التعلم الآلي",
            "Deep Learning": "التعلم العميق",
            "Natural Language": "اللغة الطبيعية",
            "Natural Language Processing": "معالجة اللغة الطبيعية",
            "Chatbot": "روبوت الدردشة",
            "Chatbots": "روبوتات الدردشة",
            "Bot": "الروبوت",
            "Bots": "الروبوتات",
            "Voicebot": "روبوت الصوت",
            "Voicebots": "روبوتات الصوت",
            "Virtual Assistant": "المساعد الافتراضي",
            "Virtual Assistants": "المساعدون الافتراضيون",
            "Assistant": "المساعد",
            "Assistants": "المساعدون",
            "Algorithm": "الخوارزمية",
            "Algorithms": "الخوارزميات",
            "Model": "النموذج",
            "Models": "النماذج",
            "Training": "التدريب",
            "Learning": "التعلم",
            "Prediction": "التنبؤ",
            "Predictions": "التنبؤات",
            "Analysis": "التحليل",
            "Analytics": "التحليلات",
            "Insights": "الرؤى",
            "Intelligence": "الذكاء",
            "Data": "البيانات",
            "Database": "قاعدة البيانات",
            "Databases": "قواعد البيانات",
            "Cloud": "السحابة",
            "Server": "الخادم",
            "Servers": "الخوادم",
            "Network": "الشبكة",
            "Networks": "الشبكات",
            "Internet": "الإنترنت",
            "Web": "الويب",
            "Website": "الموقع الإلكتروني",
            "Websites": "المواقع الإلكترونية",
            "Mobile": "الجوال",
            "Desktop": "سطح المكتب",
            "Tablet": "الجهاز اللوحي",
            "Device": "الجهاز",
            "Devices": "الأجهزة",
            
            # Time & Availability
            "Available": "متاح",
            "Availability": "التوافر",
            "Unavailable": "غير متاح",
            "Online": "متصل",
            "Offline": "غير متصل",
            "Active": "نشط",
            "Inactive": "غير نشط",
            "Live": "مباشر",
            "Real-time": "الوقت الفعلي",
            "Real time": "الوقت الفعلي",
            "Instant": "فوري",
            "Immediate": "فوري",
            "Quick": "سريع",
            "Fast": "سريع",
            "Slow": "بطيء",
            "Now": "الآن",
            "Today": "اليوم",
            "Tomorrow": "غداً",
            "Yesterday": "أمس",
            "Daily": "يومي",
            "Weekly": "أسبوعي",
            "Monthly": "شهري",
            "Yearly": "سنوي",
            "Annual": "سنوي",
            "Always": "دائماً",
            "Never": "أبداً",
            "Sometimes": "أحياناً",
            "Often": "غالباً",
            "Rarely": "نادراً",
            "Usually": "عادة",
            "Frequently": "بشكل متكرر",
            "Occasionally": "أحياناً",
            "Continuous": "مستمر",
            "Seamless": "سلس",
            "Smooth": "سلس",
            "Efficient": "فعال",
            "Effective": "فعال",
            "Productive": "منتج",
            "Optimized": "محسّن",
            
            # Status & States
            "New": "جديد",
            "Old": "قديم",
            "Current": "الحالي",
            "Previous": "السابق",
            "Latest": "الأحدث",
            "Recent": "الأخير",
            "Upcoming": "القادم",
            "Pending": "قيد الانتظار",
            "Processing": "قيد المعالجة",
            "Complete": "مكتمل",
            "Completed": "مكتمل",
            "Incomplete": "غير مكتمل",
            "Success": "نجاح",
            "Successful": "ناجح",
            "Failed": "فشل",
            "Error": "خطأ",
            "Warning": "تحذير",
            "Info": "معلومات",
            "Information": "معلومات",
            "Important": "مهم",
            "Critical": "حرج",
            "Urgent": "عاجل",
            "High": "عالي",
            "Medium": "متوسط",
            "Low": "منخفض",
            "Priority": "الأولوية",
            "Status": "الحالة",
            "State": "الحالة",
            "Condition": "الشرط",
            "Mode": "الوضع",
            "Type": "النوع",
            "Category": "الفئة",
            "Categories": "الفئات",
            "Class": "الفئة",
            "Group": "المجموعة",
            "Groups": "المجموعات",
            "Level": "المستوى",
            "Levels": "المستويات",
            "Grade": "الدرجة",
            "Rank": "الرتبة",
            "Position": "الموقع",
            "Location": "الموقع",
            "Place": "المكان",
            "Area": "المنطقة",
            "Region": "المنطقة",
            "Zone": "المنطقة",
            "Section": "القسم",
            "Department": "القسم",
            
            # Actions & Operations
            "Create": "إنشاء",
            "Build": "بناء",
            "Make": "صنع",
            "Generate": "توليد",
            "Add": "إضافة",
            "Remove": "إزالة",
            "Delete": "حذف",
            "Edit": "تعديل",
            "Modify": "تعديل",
            "Change": "تغيير",
            "Update": "تحديث",
            "Upgrade": "ترقية",
            "Install": "تثبيت",
            "Setup": "إعداد",
            "Configure": "تكوين",
            "Customize": "تخصيص",
            "Deploy": "نشر",
            "Launch": "إطلاق",
            "Run": "تشغيل",
            "Execute": "تنفيذ",
            "Process": "معالجة",
            "Handle": "معالجة",
            "Manage": "إدارة",
            "Control": "التحكم",
            "Monitor": "مراقبة",
            "Track": "تتبع",
            "Follow": "متابعة",
            "Watch": "مشاهدة",
            "Observe": "مراقبة",
            "Analyze": "تحليل",
            "Evaluate": "تقييم",
            "Assess": "تقييم",
            "Measure": "قياس",
            "Calculate": "حساب",
            "Count": "عد",
            "Compare": "مقارنة",
            "Match": "مطابقة",
            "Search": "بحث",
            "Find": "إيجاد",
            "Locate": "تحديد الموقع",
            "Identify": "تحديد",
            "Recognize": "التعرف",
            "Detect": "اكتشاف",
            "Discover": "اكتشاف",
            "Connect": "اتصال",
            "Link": "ربط",
            "Join": "انضمام",
            "Merge": "دمج",
            "Combine": "دمج",
            "Integrate": "تكامل",
            "Sync": "مزامنة",
            "Synchronize": "مزامنة",
            "Import": "استيراد",
            "Export": "تصدير",
            "Transfer": "نقل",
            "Move": "نقل",
            "Copy": "نسخ",
            "Paste": "لصق",
            "Share": "مشاركة",
            "Send": "إرسال",
            "Receive": "استقبال",
            "Get": "الحصول على",
            "Fetch": "جلب",
            "Retrieve": "استرجاع",
            "Store": "تخزين",
            "Save": "حفظ",
            "Keep": "الاحتفاظ",
            "Maintain": "صيانة",
            "Preserve": "حفظ",
            "Protect": "حماية",
            "Secure": "تأمين",
            "Encrypt": "تشفير",
            "Decrypt": "فك التشفير",
            "Authenticate": "المصادقة",
            "Authorize": "التفويض",
            "Verify": "التحقق",
            "Validate": "التحقق من الصحة",
            "Confirm": "تأكيد",
            "Approve": "الموافقة",
            "Reject": "رفض",
            "Accept": "قبول",
            "Decline": "رفض",
            "Allow": "السماح",
            "Deny": "منع",
            "Grant": "منح",
            "Revoke": "إلغاء",
            "Enable": "تمكين",
            "Disable": "تعطيل",
            "Activate": "تفعيل",
            "Deactivate": "إلغاء التفعيل",
            "Start": "بدء",
            "Stop": "إيقاف",
            "Pause": "إيقاف مؤقت",
            "Resume": "استئناف",
            "Continue": "متابعة",
            "Finish": "إنهاء",
            "Complete": "إكمال",
            "Done": "تم",
            "Ready": "جاهز",
            "Prepare": "تحضير",
            "Initialize": "تهيئة",
            "Load": "تحميل",
            "Reload": "إعادة تحميل",
            "Refresh": "تحديث",
            "Reset": "إعادة تعيين",
            "Restart": "إعادة تشغيل",
            "Retry": "إعادة المحاولة",
            "Undo": "تراجع",
            "Redo": "إعادة",
            "Repeat": "تكرار",
            "Duplicate": "تكرار",
            "Clone": "استنساخ",
            "Backup": "نسخ احتياطي",
            "Restore": "استعادة",
            "Recover": "استرداد",
            "Fix": "إصلاح",
            "Repair": "إصلاح",
            "Solve": "حل",
            "Resolve": "حل",
            "Troubleshoot": "استكشاف الأخطاء وإصلاحها",
            "Debug": "تصحيح الأخطاء",
            "Test": "اختبار",
            "Check": "فحص",
            "Inspect": "فحص",
            "Audit": "تدقيق",
            "Review": "مراجعة",
            "Examine": "فحص",
            "Scan": "مسح",
            "Filter": "تصفية",
            "Sort": "ترتيب",
            "Order": "ترتيب",
            "Arrange": "ترتيب",
            "Organize": "تنظيم",
            "Categorize": "تصنيف",
            "Classify": "تصنيف",
            "Tag": "وسم",
            "Label": "تسمية",
            "Mark": "وضع علامة",
            "Flag": "وضع علامة",
            "Highlight": "تسليط الضوء",
            "Select": "تحديد",
            "Choose": "اختيار",
            "Pick": "اختيار",
            "Opt": "اختيار",
            
            # Common Phrases
            "Welcome": "مرحباً",
            "Hello": "مرحباً",
            "Hi": "مرحباً",
            "Goodbye": "وداعاً",
            "Bye": "وداعاً",
            "Thank you": "شكراً لك",
            "Thanks": "شكراً",
            "Please": "من فضلك",
            "Sorry": "آسف",
            "Excuse me": "عذراً",
            "Yes": "نعم",
            "No": "لا",
            "Maybe": "ربما",
            "Perhaps": "ربما",
            "Possibly": "ربما",
            "Probably": "على الأرجح",
            "Definitely": "بالتأكيد",
            "Certainly": "بالتأكيد",
            "Sure": "بالتأكيد",
            "Of course": "بالطبع",
            "Absolutely": "بالتأكيد",
            "Exactly": "بالضبط",
            "Correct": "صحيح",
            "Right": "صحيح",
            "Wrong": "خطأ",
            "Good": "جيد",
            "Great": "رائع",
            "Excellent": "ممتاز",
            "Perfect": "مثالي",
            "Amazing": "مذهل",
            "Awesome": "رائع",
            "Wonderful": "رائع",
            "Fantastic": "رائع",
            "Beautiful": "جميل",
            "Nice": "لطيف",
            "Bad": "سيء",
            "Poor": "ضعيف",
            "Terrible": "فظيع",
            "Horrible": "فظيع",
            "Awful": "فظيع",
            
            # Business Phrases
            "Customer Support": "دعم العملاء",
            "Customer Service": "خدمة العملاء",
            "Technical Support": "الدعم الفني",
            "Help Center": "مركز المساعدة",
            "Knowledge Base": "قاعدة المعرفة",
            "Best Practices": "أفضل الممارسات",
            "Use Cases": "حالات الاستخدام",
            "Use Case": "حالة الاستخدام",
            "Case Study": "دراسة حالة",
            "Case Studies": "دراسات الحالة",
            "Success Story": "قصة نجاح",
            "Success Stories": "قصص النجاح",
            "Testimonial": "شهادة",
            "Testimonials": "الشهادات",
            "Frequently Asked Questions": "الأسئلة الشائعة",
            "Terms of Service": "شروط الخدمة",
            "Privacy Policy": "سياسة الخصوصية",
            "Cookie Policy": "سياسة ملفات تعريف الارتباط",
            "Data Protection": "حماية البيانات",
            "Security Policy": "سياسة الأمان",
            "Compliance": "الامتثال",
            "Certification": "الشهادة",
            "Certifications": "الشهادات",
            "License": "الترخيص",
            "Licenses": "التراخيص",
            "Agreement": "الاتفاقية",
            "Contract": "العقد",
            "Terms": "الشروط",
            "Conditions": "الأحكام",
            "Requirements": "المتطلبات",
            "Specifications": "المواصفات",
            "Standards": "المعايير",
            "Guidelines": "الإرشادات",
            "Rules": "القواعد",
            "Regulations": "اللوائح",
            "Policies": "السياسات",
            "Procedures": "الإجراءات",
            "Workflow": "سير العمل",
            "Process": "العملية",
            "Strategy": "الاستراتيجية",
            "Plan": "الخطة",
            "Goal": "الهدف",
            "Objective": "الهدف",
            "Target": "الهدف",
            "Mission": "المهمة",
            "Vision": "الرؤية",
            "Value": "القيمة",
            "Values": "القيم",
            "Benefit": "الفائدة",
            "Benefits": "الفوائد",
            "Advantage": "الميزة",
            "Advantages": "المزايا",
            "Feature": "الميزة",
            "Features": "الميزات",
            
            # Specific Phrases
            "Getting Started": "البدء",
            "How It Works": "كيف يعمل",
            "What's New": "ما الجديد",
            "Coming Soon": "قريباً",
            "Under Construction": "تحت الإنشاء",
            "Work in Progress": "العمل جارٍ",
            "Beta Version": "النسخة التجريبية",
            "Early Access": "الوصول المبكر",
            "Limited Time": "لفترة محدودة",
            "Limited Offer": "عرض محدود",
            "Special Offer": "عرض خاص",
            "Exclusive Offer": "عرض حصري",
            "Free Forever": "مجاني للأبد",
            "No Credit Card Required": "لا حاجة لبطاقة ائتمان",
            "Cancel Anytime": "إلغاء في أي وقت",
            "Money Back Guarantee": "ضمان استرداد الأموال",
            "Risk Free": "بدون مخاطر",
            "Trusted by": "موثوق به من قبل",
            "Used by": "مستخدم من قبل",
            "Loved by": "محبوب من قبل",
            "Recommended by": "موصى به من قبل",
            "Featured in": "مميز في",
            "As seen on": "كما شوهد على",
            "Join thousands": "انضم إلى الآلاف",
            "Join millions": "انضم إلى الملايين",
            
            # Multi-word phrases
            "All rights reserved": "جميع الحقوق محفوظة",
            "Made with": "صُنع بـ",
            "Built with": "مبني بـ",
            "Powered by": "مدعوم من",
            "Built for": "مصمم لـ",
            "Designed for": "مصمم لـ",
            "Created for": "تم إنشاؤه لـ",
            "Perfect for": "مثالي لـ",
            "Ideal for": "مثالي لـ",
            "Best for": "الأفضل لـ",
            "Ready to": "جاهز لـ",
            "Easy to": "سهل الـ",
            "Simple to": "بسيط الـ",
            "Quick to": "سريع الـ",
            "Free to": "مجاني الـ",
            "Learn how to": "تعلم كيفية",
            "Discover how": "اكتشف كيف",
            "Find out": "اكتشف",
            "Get started with": "ابدأ مع",
            "Sign up for": "سجل في",
            "Sign in to": "سجل الدخول إلى",
            "Log in to": "سجل الدخول إلى",
            "Connect with": "تواصل مع",
            "Talk to": "تحدث إلى",
            "Chat with": "تحدث مع",
            "Schedule a": "جدول",
            "Book a": "احجز",
            "Request a": "اطلب",
            "Get a": "احصل على",
            "Download the": "قم بتنزيل",
            "Install the": "قم بتثبيت",
            "Set up": "إعداد",
            "Turn on": "تشغيل",
            "Turn off": "إيقاف",
            "Switch to": "التبديل إلى",
            "Upgrade to": "الترقية إلى",
            "Move to": "الانتقال إلى",
            "Migrate to": "الترحيل إلى",
            "Back to": "العودة إلى",
            "Go to": "الذهاب إلى",
            "Navigate to": "الانتقال إلى",
            "Click here": "انقر هنا",
            "Tap here": "انقر هنا",
            "Press here": "اضغط هنا",
            "See more": "شاهد المزيد",
            "Show less": "أظهر أقل",
            "Load more": "تحميل المزيد",
            "View details": "عرض التفاصيل",
            "More info": "المزيد من المعلومات",
            "Less info": "معلومات أقل",
            "Full details": "التفاصيل الكاملة",
            "Quick view": "عرض سريع",
            "Preview": "معاينة",
            "Overview": "نظرة عامة",
            "Summary": "ملخص",
            "Details": "التفاصيل",
            "Description": "الوصف",
            "Instructions": "التعليمات",
            "Tutorial": "البرنامج التعليمي",
            "Guide": "الدليل",
            "Manual": "الدليل",
            "Documentation": "التوثيق",
            "Reference": "المرجع",
            "Examples": "الأمثلة",
            "Sample": "عينة",
            "Demo": "عرض تجريبي",
            "Trial": "تجربة",
            "Test": "اختبار",
            "Sandbox": "بيئة الاختبار",
            "Playground": "ساحة اللعب",
            "Environment": "البيئة",
            "Production": "الإنتاج",
            "Development": "التطوير",
            "Staging": "التدريج",
            "Testing": "الاختبار",
            "Debug": "تصحيح الأخطاء",
            "Maintenance": "الصيانة",
            "Downtime": "وقت التوقف",
            "Uptime": "وقت التشغيل",
            "Performance": "الأداء",
            "Speed": "السرعة",
            "Efficiency": "الكفاءة",
            "Reliability": "الموثوقية",
            "Scalability": "قابلية التوسع",
            "Flexibility": "المرونة",
            "Compatibility": "التوافق",
            "Accessibility": "إمكانية الوصول",
            "Usability": "سهولة الاستخدام",
            "User Experience": "تجربة المستخدم",
            "User Interface": "واجهة المستخدم",
            "User Friendly": "سهل الاستخدام",
            "Mobile Friendly": "متوافق مع الجوال",
            "Responsive": "متجاوب",
            "Cross Platform": "عبر المنصات",
            "Multi Platform": "متعدد المنصات",
            "All in One": "الكل في واحد",
            "End to End": "من البداية إلى النهاية",
            "Out of the Box": "جاهز للاستخدام",
            "Plug and Play": "التوصيل والتشغيل",
            "Drag and Drop": "السحب والإفلات",
            "Point and Click": "النقر والتأشير",
            "One Click": "نقرة واحدة",
            "Single Click": "نقرة واحدة",
            "Double Click": "نقرة مزدوجة",
            "Right Click": "النقر بزر الماوس الأيمن",
            "Left Click": "النقر بزر الماوس الأيسر",
            "Long Press": "الضغط الطويل",
            "Swipe": "التمرير",
            "Scroll": "التمرير",
            "Zoom": "التكبير",
            "Pinch": "القرص",
            "Rotate": "التدوير",
            "Resize": "تغيير الحجم",
            "Minimize": "تصغير",
            "Maximize": "تكبير",
            "Full Screen": "ملء الشاشة",
            "Exit Full Screen": "الخروج من وضع ملء الشاشة",
            "Pop Up": "نافذة منبثقة",
            "Drop Down": "قائمة منسدلة",
            "Menu": "القائمة",
            "Submenu": "القائمة الفرعية",
            "Sidebar": "الشريط الجانبي",
            "Header": "الرأس",
            "Footer": "التذييل",
            "Navigation": "التنقل",
            "Breadcrumb": "مسار التنقل",
            "Pagination": "ترقيم الصفحات",
            "Search Bar": "شريط البحث",
            "Search Box": "مربع البحث",
            "Text Box": "مربع النص",
            "Input Field": "حقل الإدخال",
            "Form": "النموذج",
            "Button": "الزر",
            "Link": "الرابط",
            "Icon": "الأيقونة",
            "Image": "الصورة",
            "Video": "الفيديو",
            "Audio": "الصوت",
            "File": "الملف",
            "Folder": "المجلد",
            "Document": "المستند",
            "Spreadsheet": "جدول البيانات",
            "Presentation": "العرض التقديمي",
            "Report": "التقرير",
            "Chart": "الرسم البياني",
            "Graph": "الرسم البياني",
            "Table": "الجدول",
            "List": "القائمة",
            "Grid": "الشبكة",
            "Card": "البطاقة",
            "Badge": "الشارة",
            "Tag": "الوسم",
            "Label": "التسمية",
            "Tooltip": "التلميح",
            "Notification": "الإشعار",
            "Alert": "التنبيه",
            "Message": "الرسالة",
            "Error Message": "رسالة خطأ",
            "Success Message": "رسالة نجاح",
            "Warning Message": "رسالة تحذير",
            "Info Message": "رسالة معلومات",
            "Confirmation": "التأكيد",
            "Dialog": "مربع الحوار",
            "Modal": "النافذة المشروطة",
            "Overlay": "الطبقة العلوية",
            "Backdrop": "الخلفية",
            "Loading": "جاري التحميل",
            "Processing": "جاري المعالجة",
            "Saving": "جاري الحفظ",
            "Updating": "جاري التحديث",
            "Deleting": "جاري الحذف",
            "Searching": "جاري البحث",
            "Fetching": "جاري الجلب",
            "Syncing": "جاري المزامنة",
            "Uploading": "جاري التحميل",
            "Downloading": "جاري التنزيل",
            "Installing": "جاري التثبيت",
            "Configuring": "جاري التكوين",
            "Initializing": "جاري التهيئة",
            "Starting": "جاري البدء",
            "Stopping": "جاري الإيقاف",
            "Restarting": "جاري إعادة التشغيل",
            "Connecting": "جاري الاتصال",
            "Disconnecting": "جاري قطع الاتصال",
            "Authenticating": "جاري المصادقة",
            "Authorizing": "جاري التفويض",
            "Verifying": "جاري التحقق",
            "Validating": "جاري التحقق من الصحة",
            
            # Long phrases needing translation
            "Losing Leads": "فقدان العملاء المحتملين",
            "in a Maze of": "في متاهة من",
            "and Inboxes": "وصناديق الوارد",
            "Fragmented": "مجزأ",
            "Lost Revenue": "خسارة الإيرادات",
            "Operational Overload": "الحمل التشغيلي الزائد",
            "is stretched thin": "مرهق",
            "managing too many": "إدارة الكثير من",
            "instead of focusing on": "بدلاً من التركيز على",
            "after-hours": "بعد ساعات العمل",
            "slow responses mean": "الردود البطيئة تعني",
            "frustrated": "محبط",
            "creates chaos": "يخلق الفوضى",
            "wastes time": "يضيع الوقت",
            "Unified Omni-Channel Hub": "مركز موحد متعدد القنوات",
            "Copilot Your": "شارك في قيادة",
            "deployment": "النشر",
            "handoff": "التسليم",
            "improvement": "التحسين",
            "Ready to Transform Your": "هل أنت مستعد لتحويل",
            "that fit your": "التي تناسب",
            "needs": "احتياجاتك",
            "with our": "مع",
            "plan": "خطتنا"
        }
        
    def should_preserve(self, text: str) -> bool:
        """Check if text should be preserved as-is"""
        text_clean = text.strip()
        
        # Preserve exact company/product names
        if text_clean in self.preserve_exact:
            return True
        
        # Preserve technical acronyms
        if text_clean in self.technical_acronyms:
            return True
        
        # Preserve patterns
        patterns = [
            r'^https?://',  # URLs
            r'^www\.',  # Websites
            r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$',  # Emails
            r'^\+?\d[\d\s\-\(\)]+$',  # Phone numbers
            r'^\$[\d,]+\.?\d*$',  # Currency
            r'^\d+%$',  # Percentages
            r'^#[A-Fa-f0-9]{3,6}$',  # Hex colors
            r'^v?\d+\.\d+',  # Version numbers
            r'^\d+$',  # Pure numbers
        ]
        
        for pattern in patterns:
            if re.match(pattern, text_clean):
                return True
        
        # Preserve if no alphabetic characters
        if not re.search(r'[a-zA-Z]', text_clean):
            return True
            
        return False
    
    def translate_text(self, text: str) -> str:
        """Translate text while preserving special content"""
        if not text or not text.strip():
            return text
        
        # Check if entire string should be preserved
        if self.should_preserve(text):
            return text
        
        result = text
        
        # Apply translations (longest first to avoid partial replacements)
        for english, arabic in sorted(self.translations.items(), key=lambda x: len(x[0]), reverse=True):
            # Create word boundary pattern for accurate matching
            pattern = r'\b' + re.escape(english) + r'\b'
            result = re.sub(pattern, arabic, result, flags=re.IGNORECASE)
        
        return result
    
    def process_json_value(self, value: Any) -> Any:
        """Process JSON value recursively"""
        if isinstance(value, str):
            return self.translate_text(value)
        elif isinstance(value, dict):
            return {key: self.process_json_value(val) for key, val in value.items()}
        elif isinstance(value, list):
            return [self.process_json_value(item) for item in value]
        else:
            return value

def main():
    """Main function to complete Arabic translation"""
    import os
    current_dir = os.path.dirname(os.path.abspath(__file__))
    locales_dir = os.path.join(current_dir, 'public', 'locales')
    
    input_file = os.path.join(locales_dir, 'ar.json')
    output_file = os.path.join(locales_dir, 'ar.json')
    
    print("Loading ar.json...")
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    translator = CompleteArabicTranslator()
    
    print("Completing Arabic translations...")
    processed_data = translator.process_json_value(data)
    
    print("Saving completed translations...")
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(processed_data, f, ensure_ascii=False, indent=2)
    
    print("✅ Translation completed successfully!")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
