#!/usr/bin/env python3
import json
import re

def should_preserve(text):
    """Check if text should be preserved (not translated)"""
    if not isinstance(text, str):
        return True
        
    # Preserve empty strings
    if not text.strip():
        return True
    
    # Preserve specific product/company names only if they are the entire text
    preserve_exact = [
        'Seasalt.ai', 'SeaChat', 'SeaMeet', 'SeaX', 'SeaVoice', 'SeaSuite', 'SeaHealth',
        'WhatsApp', 'Instagram', 'Facebook', 'Messenger', 'LINE', 'Line',
        'Telegram', 'WeChat', 'Discord', 'Slack', 'Microsoft Teams',
        'Twilio', 'Google', 'Aircall', 'RingCentral', 'Genesys', 'Five9',
        'HubSpot', 'Salesforce', 'Zendesk', 'Pipedrive', 'Monday.com',
        'ClickUp', 'Airtable', 'Notion', 'Asana', 'Trello', 'Stripe',
        'PayPal', 'Shopify', 'WooCommerce', 'BigCommerce', 'Magento',
        'WordPress', 'Drupal', 'Joomla', 'React', 'Angular', 'Vue',
        'AWS', 'Azure', 'GCP', 'GitHub', 'GitLab', 'Bitbucket', 'Jira', 'Confluence',
        'API', 'SMS', 'HIPAA', 'GDPR', 'SOC 2', 'ISO', '10DLC', 'A2P', 'P2P',
        'Seattle', 'WA', 'USA', 'API References', 'Product Wiki'
    ]
    
    if text.strip() in preserve_exact:
        return True
    
    # Preserve URLs, emails, variables, and specific patterns
    if (re.match(r'^https?://', text) or 
        '@' in text and '.' in text or  # Email
        re.match(r'^\{\{[^}]+\}\}$', text) or  # Template variables like {{year}}
        re.match(r'^#[A-Z0-9]+$', text) or  # Hex codes or IDs
        re.match(r'^[A-Z0-9_]+$', text) or  # Constants
        re.match(r'^\+\d+[\s\-\(\)0-9A-Z]+$', text) or  # Phone numbers
        re.match(r'^\d+[%$€£¥]?$', text) or  # Pure numbers with currency
        re.match(r'^[0-9]+DLC$', text) or  # 10DLC
        text == 'xxxxx' or text == '8XX'):  # Technical placeholders
        return True
    
    # Check for author names (First Last pattern)
    if re.match(r'^[A-Z][a-z]+\s+[A-Z][a-z]+(-[A-Z][a-z]+)?$', text.strip()):
        # Common phrases that should be translated
        translate_these = ['Customer Support', 'Customer Service', 'Technical Support', 
                          'Sales Marketing', 'Human Resources', 'Product Manager',
                          'Customer Success', 'Solution Architect', 'Operations Director']
        if text not in translate_these:
            return True
    
    return False

def get_comprehensive_translations():
    """Returns comprehensive German translations"""
    return {
        # Extended comprehensive translations
        'Home': 'Startseite',
        'Products': 'Produkte',
        'Product': 'Produkt',
        'Solutions': 'Lösungen',
        'Solution': 'Lösung',
        'Pricing': 'Preise',
        'Price': 'Preis',
        'Resources': 'Ressourcen',
        'Company': 'Unternehmen',
        'Contact': 'Kontakt',
        'About': 'Über uns',
        'About Us': 'Über uns',
        'Careers': 'Karriere',
        'Career': 'Karriere',
        'Blog': 'Blog',
        'Help': 'Hilfe',
        'Support': 'Support',
        'Documentation': 'Dokumentation',
        'FAQ': 'Häufige Fragen',
        'FAQs': 'Häufige Fragen',
        'Privacy': 'Datenschutz',
        'Privacy Policy': 'Datenschutzrichtlinie',
        'Terms': 'Bedingungen',
        'Terms of Service': 'Nutzungsbedingungen',
        'Legal': 'Rechtliches',
        'Security': 'Sicherheit',
        'Compliance': 'Compliance',
        
        # Actions and buttons
        'Book a Demo': 'Demo buchen',
        'Book Demo': 'Demo buchen',
        'Book A Demo': 'Demo buchen',
        'Schedule Demo': 'Demo vereinbaren',
        'See Demo': 'Demo ansehen',
        'Watch Demo': 'Demo ansehen',
        'Sign Up': 'Registrieren',
        'Sign In': 'Anmelden',
        'Sign Up Now': 'Jetzt registrieren',
        'Log In': 'Anmelden',
        'Log Out': 'Abmelden',
        'Login': 'Anmelden',
        'Logout': 'Abmelden',
        'Register': 'Registrieren',
        'Get Started': 'Jetzt starten',
        'Start Now': 'Jetzt starten',
        'Learn More': 'Mehr erfahren',
        'Try for Free': 'Kostenlos testen',
        'Try Free': 'Kostenlos testen',
        'Start Free Trial': 'Kostenlose Testversion starten',
        'Start Trial': 'Testversion starten',
        'Start for Free': 'Kostenlos starten',
        'Download': 'Herunterladen',
        'Upload': 'Hochladen',
        'Submit': 'Absenden',
        'Send': 'Senden',
        'Save': 'Speichern',
        'Cancel': 'Abbrechen',
        'Continue': 'Fortfahren',
        'Next': 'Weiter',
        'Previous': 'Zurück',
        'Back': 'Zurück',
        'Back to': 'Zurück zu',
        'Close': 'Schließen',
        'Edit': 'Bearbeiten',
        'Delete': 'Löschen',
        'Remove': 'Entfernen',
        'Add': 'Hinzufügen',
        'Create': 'Erstellen',
        'Update': 'Aktualisieren',
        'Refresh': 'Aktualisieren',
        'Search': 'Suchen',
        'Filter': 'Filtern',
        'Sort': 'Sortieren',
        'Export': 'Exportieren',
        'Import': 'Importieren',
        'Share': 'Teilen',
        'View': 'Ansehen',
        'View All': 'Alle ansehen',
        'See All': 'Alle ansehen',
        'Show All': 'Alle anzeigen',
        'Expand': 'Erweitern',
        'Collapse': 'Einklappen',
        
        # Business terms
        'Enterprise': 'Unternehmen',
        'Business': 'Geschäft',
        'Small Business': 'Kleinunternehmen',
        'Small Businesses': 'Kleinunternehmen',
        'Medium Business': 'Mittelständisches Unternehmen',
        'Large Enterprise': 'Großunternehmen',
        'Customer': 'Kunde',
        'Customers': 'Kunden',
        'Client': 'Klient',
        'Clients': 'Klienten',
        'User': 'Benutzer',
        'Users': 'Benutzer',
        'Team': 'Team',
        'Teams': 'Teams',
        'Employee': 'Mitarbeiter',
        'Employees': 'Mitarbeiter',
        'Staff': 'Personal',
        'Manager': 'Manager',
        'Admin': 'Administrator',
        'Administrator': 'Administrator',
        'Owner': 'Inhaber',
        'Partner': 'Partner',
        'Partners': 'Partner',
        'Vendor': 'Anbieter',
        'Supplier': 'Lieferant',
        'Stakeholder': 'Interessenvertreter',
        'Department': 'Abteilung',
        'Organization': 'Organisation',
        'SME': 'KMU',
        'SMEs': 'KMUs',
        'Startup': 'Startup',
        'Agency': 'Agentur',
        
        # Sales & Marketing
        'Sales': 'Vertrieb',
        'Marketing': 'Marketing',
        'Lead': 'Lead',
        'Leads': 'Leads',
        'Lead Generation': 'Lead-Generierung',
        'Prospect': 'Interessent',
        'Opportunity': 'Chance',
        'Deal': 'Geschäft',
        'Deals': 'Geschäfte',
        'Pipeline': 'Pipeline',
        'Funnel': 'Trichter',
        'Campaign': 'Kampagne',
        'Campaigns': 'Kampagnen',
        'Conversion': 'Konversion',
        'Revenue': 'Umsatz',
        'Growth': 'Wachstum',
        'ROI': 'ROI',
        'Customer Service': 'Kundendienst',
        'Customer Support': 'Kundensupport',
        'Customer Experience': 'Kundenerfahrung',
        'Customer Success': 'Kundenerfolg',
        'Customer Engagement': 'Kundenbindung',
        'Customer Satisfaction': 'Kundenzufriedenheit',
        'Sales & Marketing': 'Vertrieb & Marketing',
        
        # Communication
        'Chat': 'Chat',
        'Chats': 'Chats',
        'Voice': 'Sprache',
        'Call': 'Anruf',
        'Calls': 'Anrufe',
        'Phone': 'Telefon',
        'Phone Call': 'Telefonanruf',
        'Phone Calls': 'Telefonanrufe',
        'Message': 'Nachricht',
        'Messages': 'Nachrichten',
        'Email': 'E-Mail',
        'Emails': 'E-Mails',
        'Text': 'Text',
        'Video': 'Video',
        'Meeting': 'Meeting',
        'Meetings': 'Meetings',
        'Conference': 'Konferenz',
        'Webinar': 'Webinar',
        'Conversation': 'Gespräch',
        'Conversations': 'Gespräche',
        'Communication': 'Kommunikation',
        'Communications': 'Kommunikation',
        'Notification': 'Benachrichtigung',
        'Notifications': 'Benachrichtigungen',
        'Alert': 'Warnung',
        'Alerts': 'Warnungen',
        'Response': 'Antwort',
        'Responses': 'Antworten',
        
        # Features & Technology
        'Features': 'Funktionen',
        'Feature': 'Funktion',
        'Benefits': 'Vorteile',
        'Benefit': 'Vorteil',
        'Capabilities': 'Fähigkeiten',
        'Functionality': 'Funktionalität',
        'Integration': 'Integration',
        'Integrations': 'Integrationen',
        'Plugin': 'Plugin',
        'Extension': 'Erweiterung',
        'App': 'App',
        'Application': 'Anwendung',
        'Platform': 'Plattform',
        'System': 'System',
        'Software': 'Software',
        'Tool': 'Werkzeug',
        'Tools': 'Werkzeuge',
        'Service': 'Dienst',
        'Services': 'Dienste',
        'Dashboard': 'Dashboard',
        'Interface': 'Schnittstelle',
        'Workflow': 'Arbeitsablauf',
        'Process': 'Prozess',
        'Automation': 'Automatisierung',
        'Automate': 'Automatisieren',
        'Automated': 'Automatisiert',
        'Automatic': 'Automatisch',
        'Manual': 'Manuell',
        'Custom': 'Individuell',
        'Customized': 'Angepasst',
        'Personalized': 'Personalisiert',
        'Advanced': 'Erweitert',
        'Basic': 'Basis',
        'Standard': 'Standard',
        'Premium': 'Premium',
        'Professional': 'Professional',
        'Enterprise': 'Unternehmen',
        
        # AI & Technology
        'AI': 'KI',
        'Artificial Intelligence': 'Künstliche Intelligenz',
        'Machine Learning': 'Maschinelles Lernen',
        'Deep Learning': 'Deep Learning',
        'Natural Language Processing': 'Natürliche Sprachverarbeitung',
        'Bot': 'Bot',
        'Chatbot': 'Chatbot',
        'Voicebot': 'Sprachbot',
        'Virtual Assistant': 'Virtueller Assistent',
        'Digital Assistant': 'Digitaler Assistent',
        'Agent': 'Agent',
        'Agents': 'Agenten',
        'Human Agent': 'Menschlicher Agent',
        'Live Agent': 'Live-Agent',
        'AI Agent': 'KI-Agent',
        'AI Agents': 'KI-Agenten',
        
        # Analytics & Data
        'Analytics': 'Analytik',
        'Analysis': 'Analyse',
        'Report': 'Bericht',
        'Reports': 'Berichte',
        'Reporting': 'Berichterstattung',
        'Metrics': 'Metriken',
        'KPI': 'KPI',
        'KPIs': 'KPIs',
        'Performance': 'Leistung',
        'Insights': 'Einblicke',
        'Data': 'Daten',
        'Database': 'Datenbank',
        'Statistics': 'Statistiken',
        'Tracking': 'Verfolgung',
        'Monitoring': 'Überwachung',
        'Real-time': 'Echtzeit',
        'Real Time': 'Echtzeit',
        'Live': 'Live',
        
        # Time
        'Day': 'Tag',
        'Days': 'Tage',
        'Week': 'Woche',
        'Weeks': 'Wochen',
        'Month': 'Monat',
        'Months': 'Monate',
        'Year': 'Jahr',
        'Years': 'Jahre',
        'Hour': 'Stunde',
        'Hours': 'Stunden',
        'Minute': 'Minute',
        'Minutes': 'Minuten',
        'Second': 'Sekunde',
        'Seconds': 'Sekunden',
        'Today': 'Heute',
        'Tomorrow': 'Morgen',
        'Yesterday': 'Gestern',
        'Daily': 'Täglich',
        'Weekly': 'Wöchentlich',
        'Monthly': 'Monatlich',
        'Yearly': 'Jährlich',
        'Annual': 'Jährlich',
        'Annually': 'Jährlich',
        
        # Pricing & Payment
        'Free': 'Kostenlos',
        'Trial': 'Testversion',
        'Free Trial': 'Kostenlose Testversion',
        'Starter': 'Starter',
        'Pro': 'Pro',
        'Plus': 'Plus',
        'Cost': 'Kosten',
        'Fee': 'Gebühr',
        'Fees': 'Gebühren',
        'Payment': 'Zahlung',
        'Billing': 'Abrechnung',
        'Invoice': 'Rechnung',
        'Subscription': 'Abonnement',
        'Plan': 'Plan',
        'Plans': 'Pläne',
        'Package': 'Paket',
        'Bundle': 'Bündel',
        'Discount': 'Rabatt',
        'Offer': 'Angebot',
        'Deal': 'Angebot',
        'Per User': 'Pro Benutzer',
        'Per Month': 'Pro Monat',
        'Per Year': 'Pro Jahr',
        'Unlimited': 'Unbegrenzt',
        'Limited': 'Begrenzt',
        
        # Industries
        'Healthcare': 'Gesundheitswesen',
        'Education': 'Bildung',
        'Finance': 'Finanzen',
        'Financial Services': 'Finanzdienstleistungen',
        'Banking': 'Bankwesen',
        'Insurance': 'Versicherung',
        'Retail': 'Einzelhandel',
        'E-commerce': 'E-Commerce',
        'Real Estate': 'Immobilien',
        'Manufacturing': 'Fertigung',
        'Technology': 'Technologie',
        'Telecommunications': 'Telekommunikation',
        'Transportation': 'Transport',
        'Logistics': 'Logistik',
        'Hospitality': 'Gastgewerbe',
        'Travel': 'Reisen',
        'Tourism': 'Tourismus',
        'Media': 'Medien',
        'Entertainment': 'Unterhaltung',
        'Government': 'Regierung',
        'Non-profit': 'Gemeinnützig',
        'Energy': 'Energie',
        'Utilities': 'Versorgung',
        'Automotive': 'Automobil',
        'Construction': 'Bauwesen',
        'Agriculture': 'Landwirtschaft',
        'Pharmaceutical': 'Pharmazie',
        
        # Common UI Elements
        'Overview': 'Übersicht',
        'Summary': 'Zusammenfassung',
        'Details': 'Details',
        'Settings': 'Einstellungen',
        'Preferences': 'Präferenzen',
        'Profile': 'Profil',
        'Account': 'Konto',
        'My Account': 'Mein Konto',
        'Menu': 'Menü',
        'Options': 'Optionen',
        'Help': 'Hilfe',
        'Info': 'Info',
        'Information': 'Information',
        'Status': 'Status',
        'Active': 'Aktiv',
        'Inactive': 'Inaktiv',
        'Enabled': 'Aktiviert',
        'Disabled': 'Deaktiviert',
        'On': 'An',
        'Off': 'Aus',
        'Yes': 'Ja',
        'No': 'Nein',
        'All': 'Alle',
        'None': 'Keine',
        'Select': 'Auswählen',
        'Selected': 'Ausgewählt',
        'Available': 'Verfügbar',
        'Unavailable': 'Nicht verfügbar',
        'Required': 'Erforderlich',
        'Optional': 'Optional',
        'Recommended': 'Empfohlen',
        'Featured': 'Empfohlen',
        'Popular': 'Beliebt',
        'New': 'Neu',
        'Latest': 'Neueste',
        'Recent': 'Kürzlich',
        'Upcoming': 'Bevorstehend',
        'Pending': 'Ausstehend',
        'Processing': 'Verarbeitung',
        'Complete': 'Vollständig',
        'Completed': 'Abgeschlossen',
        'Success': 'Erfolg',
        'Successful': 'Erfolgreich',
        'Error': 'Fehler',
        'Warning': 'Warnung',
        'Loading': 'Laden',
        'Uploading': 'Hochladen',
        'Downloading': 'Herunterladen',
        'Installing': 'Installieren',
        'Updating': 'Aktualisieren',
        'Deleting': 'Löschen',
        'Creating': 'Erstellen',
        'Saving': 'Speichern',
        'Searching': 'Suchen',
        
        # Specific phrases
        'Use Cases': 'Anwendungsfälle',
        'Use Case': 'Anwendungsfall',
        'Best Practices': 'Bewährte Methoden',
        'Getting Started': 'Erste Schritte',
        'Quick Start': 'Schnellstart',
        'Setup': 'Einrichtung',
        'Configuration': 'Konfiguration',
        'Installation': 'Installation',
        'Implementation': 'Implementierung',
        'Deployment': 'Bereitstellung',
        'Migration': 'Migration',
        'Upgrade': 'Upgrade',
        'Maintenance': 'Wartung',
        'Troubleshooting': 'Fehlerbehebung',
        'Support Center': 'Support-Center',
        'Help Center': 'Hilfe-Center',
        'Knowledge Base': 'Wissensdatenbank',
        'Community': 'Community',
        'Forum': 'Forum',
        'Blog': 'Blog',
        'News': 'Nachrichten',
        'Events': 'Veranstaltungen',
        'Webinars': 'Webinare',
        'Training': 'Schulung',
        'Certification': 'Zertifizierung',
        'Partners': 'Partner',
        'Developers': 'Entwickler',
        'APIs': 'APIs',
        'SDK': 'SDK',
        'Libraries': 'Bibliotheken',
        'Frameworks': 'Frameworks',
        'Examples': 'Beispiele',
        'Templates': 'Vorlagen',
        'Guides': 'Anleitungen',
        'Tutorials': 'Tutorials',
        'Videos': 'Videos',
        'Downloads': 'Downloads',
        'Release Notes': 'Versionshinweise',
        'Changelog': 'Änderungsprotokoll',
        'Roadmap': 'Roadmap',
        'Feedback': 'Feedback',
        'Contact Us': 'Kontaktieren Sie uns',
        'Request Demo': 'Demo anfordern',
        'Get Quote': 'Angebot anfordern',
        'Schedule Call': 'Anruf vereinbaren',
        'Chat with Us': 'Mit uns chatten',
        'Email Us': 'E-Mail senden',
        'Call Us': 'Anrufen',
        'Visit Us': 'Besuchen Sie uns',
        'Follow Us': 'Folgen Sie uns',
        'Subscribe': 'Abonnieren',
        'Newsletter': 'Newsletter',
        'Stay Updated': 'Bleiben Sie auf dem Laufenden',
        'Join': 'Beitreten',
        'Connect': 'Verbinden',
        'Discover': 'Entdecken',
        'Explore': 'Erkunden',
        'Learn': 'Lernen',
        'Compare': 'Vergleichen',
        'Choose': 'Wählen',
        'Select': 'Auswählen',
        'Customize': 'Anpassen',
        'Personalize': 'Personalisieren',
        'Optimize': 'Optimieren',
        'Improve': 'Verbessern',
        'Enhance': 'Verbessern',
        'Increase': 'Erhöhen',
        'Decrease': 'Verringern',
        'Reduce': 'Reduzieren',
        'Minimize': 'Minimieren',
        'Maximize': 'Maximieren',
        'Streamline': 'Optimieren',
        'Simplify': 'Vereinfachen',
        'Accelerate': 'Beschleunigen',
        'Transform': 'Transformieren',
        'Revolutionize': 'Revolutionieren',
        'Innovate': 'Innovieren',
        'Empower': 'Befähigen',
        'Enable': 'Ermöglichen',
        'Unlock': 'Freischalten',
        'Achieve': 'Erreichen',
        'Deliver': 'Liefern',
        'Drive': 'Vorantreiben',
        'Build': 'Aufbauen',
        'Grow': 'Wachsen',
        'Scale': 'Skalieren',
        'Expand': 'Erweitern',
        'Launch': 'Starten',
        'Deploy': 'Bereitstellen',
        'Implement': 'Implementieren',
        'Execute': 'Ausführen',
        'Manage': 'Verwalten',
        'Monitor': 'Überwachen',
        'Track': 'Verfolgen',
        'Measure': 'Messen',
        'Analyze': 'Analysieren',
        'Review': 'Überprüfen',
        'Evaluate': 'Bewerten',
        'Assess': 'Beurteilen',
        'Test': 'Testen',
        'Verify': 'Verifizieren',
        'Validate': 'Validieren',
        'Confirm': 'Bestätigen',
        'Approve': 'Genehmigen',
        'Reject': 'Ablehnen',
        'Accept': 'Akzeptieren',
        'Decline': 'Ablehnen',
        'Allow': 'Erlauben',
        'Deny': 'Verweigern',
        'Grant': 'Gewähren',
        'Revoke': 'Widerrufen',
        'Assign': 'Zuweisen',
        'Allocate': 'Zuweisen',
        'Distribute': 'Verteilen',
        'Share': 'Teilen',
        'Collaborate': 'Zusammenarbeiten',
        'Communicate': 'Kommunizieren',
        'Engage': 'Einbinden',
        'Interact': 'Interagieren',
        'Connect': 'Verbinden',
        'Integrate': 'Integrieren',
        'Link': 'Verknüpfen',
        'Sync': 'Synchronisieren',
        'Update': 'Aktualisieren',
        'Refresh': 'Aktualisieren',
        'Reload': 'Neu laden',
        'Reset': 'Zurücksetzen',
        'Restore': 'Wiederherstellen',
        'Backup': 'Sichern',
        'Archive': 'Archivieren',
        'Store': 'Speichern',
        'Retrieve': 'Abrufen',
        'Fetch': 'Abrufen',
        'Load': 'Laden',
        'Display': 'Anzeigen',
        'Show': 'Zeigen',
        'Hide': 'Verbergen',
        'Toggle': 'Umschalten',
        'Switch': 'Wechseln',
        'Change': 'Ändern',
        'Modify': 'Modifizieren',
        'Adjust': 'Anpassen',
        'Configure': 'Konfigurieren',
        'Set': 'Einstellen',
        'Define': 'Definieren',
        'Specify': 'Angeben',
        'Enter': 'Eingeben',
        'Input': 'Eingabe',
        'Output': 'Ausgabe',
        'Result': 'Ergebnis',
        'Results': 'Ergebnisse',
        'Outcome': 'Ergebnis',
        'Conclusion': 'Fazit',
        'Summary': 'Zusammenfassung',
        'Report': 'Bericht',
        'Document': 'Dokument',
        'File': 'Datei',
        'Folder': 'Ordner',
        'Directory': 'Verzeichnis',
        'Path': 'Pfad',
        'Location': 'Ort',
        'Address': 'Adresse',
        'URL': 'URL',
        'Link': 'Link',
        'Button': 'Schaltfläche',
        'Form': 'Formular',
        'Field': 'Feld',
        'Input': 'Eingabe',
        'Label': 'Beschriftung',
        'Value': 'Wert',
        'Key': 'Schlüssel',
        'Parameter': 'Parameter',
        'Variable': 'Variable',
        'Constant': 'Konstante',
        'Property': 'Eigenschaft',
        'Attribute': 'Attribut',
        'Method': 'Methode',
        'Function': 'Funktion',
        'Class': 'Klasse',
        'Object': 'Objekt',
        'Module': 'Modul',
        'Component': 'Komponente',
        'Element': 'Element',
        'Item': 'Element',
        'Entry': 'Eintrag',
        'Record': 'Datensatz',
        'Row': 'Zeile',
        'Column': 'Spalte',
        'Table': 'Tabelle',
        'List': 'Liste',
        'Array': 'Array',
        'Collection': 'Sammlung',
        'Set': 'Menge',
        'Group': 'Gruppe',
        'Category': 'Kategorie',
        'Type': 'Typ',
        'Kind': 'Art',
        'Sort': 'Sortierung',
        'Order': 'Reihenfolge',
        'Sequence': 'Sequenz',
        'Series': 'Serie',
        'Range': 'Bereich',
        'Scope': 'Umfang',
        'Level': 'Ebene',
        'Tier': 'Stufe',
        'Grade': 'Grad',
        'Rank': 'Rang',
        'Priority': 'Priorität',
        'Importance': 'Wichtigkeit',
        'Weight': 'Gewicht',
        'Size': 'Größe',
        'Length': 'Länge',
        'Width': 'Breite',
        'Height': 'Höhe',
        'Depth': 'Tiefe',
        'Volume': 'Volumen',
        'Area': 'Bereich',
        'Space': 'Raum',
        'Distance': 'Entfernung',
        'Duration': 'Dauer',
        'Period': 'Zeitraum',
        'Interval': 'Intervall',
        'Frequency': 'Häufigkeit',
        'Rate': 'Rate',
        'Speed': 'Geschwindigkeit',
        'Velocity': 'Geschwindigkeit',
        'Acceleration': 'Beschleunigung',
        'Progress': 'Fortschritt',
        'Percentage': 'Prozentsatz',
        'Ratio': 'Verhältnis',
        'Proportion': 'Anteil',
        'Average': 'Durchschnitt',
        'Mean': 'Mittelwert',
        'Median': 'Median',
        'Mode': 'Modus',
        'Sum': 'Summe',
        'Total': 'Gesamt',
        'Count': 'Anzahl',
        'Number': 'Nummer',
        'Amount': 'Betrag',
        'Quantity': 'Menge',
        'Value': 'Wert',
        'Score': 'Punktzahl',
        'Rating': 'Bewertung',
        'Grade': 'Note',
        'Mark': 'Markierung',
        'Point': 'Punkt',
        'Credit': 'Kredit',
        'Debit': 'Soll',
        'Balance': 'Saldo',
        'Budget': 'Budget',
        'Expense': 'Ausgabe',
        'Income': 'Einkommen',
        'Profit': 'Gewinn',
        'Loss': 'Verlust',
        'Gain': 'Gewinn',
        'Return': 'Rendite',
        'Investment': 'Investition',
        'Asset': 'Vermögenswert',
        'Liability': 'Verbindlichkeit',
        'Equity': 'Eigenkapital',
        'Capital': 'Kapital',
        'Fund': 'Fonds',
        'Account': 'Konto',
        'Transaction': 'Transaktion',
        'Transfer': 'Überweisung',
        'Deposit': 'Einzahlung',
        'Withdrawal': 'Auszahlung',
        'Refund': 'Rückerstattung',
        'Reimbursement': 'Erstattung',
        'Compensation': 'Entschädigung',
        'Salary': 'Gehalt',
        'Wage': 'Lohn',
        'Bonus': 'Bonus',
        'Commission': 'Provision',
        'Incentive': 'Anreiz',
        'Reward': 'Belohnung',
        'Prize': 'Preis',
        'Award': 'Auszeichnung',
        'Recognition': 'Anerkennung',
        'Achievement': 'Leistung',
        'Accomplishment': 'Erfolg',
        'Milestone': 'Meilenstein',
        'Goal': 'Ziel',
        'Objective': 'Zielsetzung',
        'Target': 'Ziel',
        'Purpose': 'Zweck',
        'Mission': 'Mission',
        'Vision': 'Vision',
        'Strategy': 'Strategie',
        'Tactic': 'Taktik',
        'Approach': 'Ansatz',
        'Method': 'Methode',
        'Technique': 'Technik',
        'Process': 'Prozess',
        'Procedure': 'Verfahren',
        'Protocol': 'Protokoll',
        'Standard': 'Standard',
        'Guideline': 'Richtlinie',
        'Rule': 'Regel',
        'Policy': 'Richtlinie',
        'Regulation': 'Verordnung',
        'Requirement': 'Anforderung',
        'Specification': 'Spezifikation',
        'Criteria': 'Kriterien',
        'Condition': 'Bedingung',
        'Term': 'Begriff',
        'Clause': 'Klausel',
        'Provision': 'Bestimmung',
        'Agreement': 'Vereinbarung',
        'Contract': 'Vertrag',
        'License': 'Lizenz',
        'Permit': 'Genehmigung',
        'Authorization': 'Autorisierung',
        'Approval': 'Genehmigung',
        'Consent': 'Zustimmung',
        'Permission': 'Erlaubnis',
        'Access': 'Zugang',
        'Entry': 'Eintritt',
        'Exit': 'Ausgang',
        'Login': 'Anmeldung',
        'Logout': 'Abmeldung',
        'Session': 'Sitzung',
        'Connection': 'Verbindung',
        'Network': 'Netzwerk',
        'Server': 'Server',
        'Client': 'Client',
        'Host': 'Host',
        'Domain': 'Domain',
        'Website': 'Webseite',
        'Page': 'Seite',
        'Screen': 'Bildschirm',
        'Window': 'Fenster',
        'Tab': 'Registerkarte',
        'Panel': 'Panel',
        'Sidebar': 'Seitenleiste',
        'Header': 'Kopfzeile',
        'Footer': 'Fußzeile',
        'Navigation': 'Navigation',
        'Breadcrumb': 'Brotkrumen',
        'Search': 'Suche',
        'Query': 'Abfrage',
        'Request': 'Anfrage',
        'Response': 'Antwort',
        'Reply': 'Antwort',
        'Comment': 'Kommentar',
        'Note': 'Notiz',
        'Remark': 'Bemerkung',
        'Annotation': 'Anmerkung',
        'Tag': 'Tag',
        'Label': 'Beschriftung',
        'Badge': 'Abzeichen',
        'Icon': 'Symbol',
        'Image': 'Bild',
        'Picture': 'Bild',
        'Photo': 'Foto',
        'Graphic': 'Grafik',
        'Illustration': 'Illustration',
        'Diagram': 'Diagramm',
        'Chart': 'Diagramm',
        'Graph': 'Graph',
        'Map': 'Karte',
        'Calendar': 'Kalender',
        'Schedule': 'Zeitplan',
        'Timeline': 'Zeitachse',
        'Agenda': 'Agenda',
        'Task': 'Aufgabe',
        'Todo': 'Zu erledigen',
        'Checklist': 'Checkliste',
        'Reminder': 'Erinnerung',
        'Notification': 'Benachrichtigung',
        'Message': 'Nachricht',
        'Email': 'E-Mail',
        'Letter': 'Brief',
        'Memo': 'Memo',
        'Report': 'Bericht',
        'Presentation': 'Präsentation',
        'Slide': 'Folie',
        'Document': 'Dokument',
        'Paper': 'Papier',
        'Article': 'Artikel',
        'Post': 'Beitrag',
        'Publication': 'Veröffentlichung',
        'Edition': 'Ausgabe',
        'Version': 'Version',
        'Release': 'Veröffentlichung',
        'Update': 'Update',
        'Patch': 'Patch',
        'Fix': 'Korrektur',
        'Bug': 'Fehler',
        'Issue': 'Problem',
        'Problem': 'Problem',
        'Challenge': 'Herausforderung',
        'Obstacle': 'Hindernis',
        'Barrier': 'Barriere',
        'Limitation': 'Einschränkung',
        'Constraint': 'Beschränkung',
        'Restriction': 'Beschränkung',
        'Boundary': 'Grenze',
        'Limit': 'Grenze',
        'Maximum': 'Maximum',
        'Minimum': 'Minimum',
        'Optimal': 'Optimal',
        'Ideal': 'Ideal',
        'Perfect': 'Perfekt',
        'Excellent': 'Ausgezeichnet',
        'Good': 'Gut',
        'Fair': 'Angemessen',
        'Poor': 'Schlecht',
        'Bad': 'Schlecht',
        'Worse': 'Schlechter',
        'Worst': 'Schlechteste',
        'Better': 'Besser',
        'Best': 'Beste',
        'Top': 'Top',
        'Bottom': 'Unten',
        'Left': 'Links',
        'Right': 'Rechts',
        'Center': 'Mitte',
        'Middle': 'Mitte',
        'Front': 'Vorne',
        'Back': 'Hinten',
        'Start': 'Start',
        'End': 'Ende',
        'Beginning': 'Anfang',
        'Finish': 'Abschluss',
        'Open': 'Öffnen',
        'Close': 'Schließen',
        'Enter': 'Betreten',
        'Exit': 'Verlassen',
        'Join': 'Beitreten',
        'Leave': 'Verlassen',
        'Arrive': 'Ankommen',
        'Depart': 'Abfahren',
        'Come': 'Kommen',
        'Go': 'Gehen',
        'Move': 'Bewegen',
        'Stay': 'Bleiben',
        'Wait': 'Warten',
        'Stop': 'Stoppen',
        'Pause': 'Pausieren',
        'Resume': 'Fortsetzen',
        'Continue': 'Fortfahren',
        'Proceed': 'Fortfahren',
        'Advance': 'Voranschreiten',
        'Retreat': 'Zurückziehen',
        'Return': 'Zurückkehren',
        'Repeat': 'Wiederholen',
        'Retry': 'Erneut versuchen',
        'Undo': 'Rückgängig',
        'Redo': 'Wiederholen',
        'Revert': 'Zurücksetzen',
        'Rollback': 'Zurückrollen',
        'Forward': 'Vorwärts',
        'Backward': 'Rückwärts',
        'Up': 'Hoch',
        'Down': 'Runter',
        'In': 'Ein',
        'Out': 'Aus',
        'Inside': 'Innen',
        'Outside': 'Außen',
        'Above': 'Über',
        'Below': 'Unter',
        'Between': 'Zwischen',
        'Among': 'Unter',
        'Within': 'Innerhalb',
        'Without': 'Ohne',
        'With': 'Mit',
        'Against': 'Gegen',
        'For': 'Für',
        'From': 'Von',
        'To': 'Zu',
        'At': 'Bei',
        'By': 'Von',
        'Of': 'Von',
        'About': 'Über',
        'Through': 'Durch',
        'Across': 'Über',
        'Along': 'Entlang',
        'Around': 'Um',
        'Behind': 'Hinter',
        'Beside': 'Neben',
        'Beyond': 'Jenseits',
        'During': 'Während',
        'Except': 'Außer',
        'Following': 'Folgend',
        'Including': 'Einschließlich',
        'Excluding': 'Ausschließlich',
        'Like': 'Wie',
        'Near': 'Nahe',
        'Next': 'Nächste',
        'Opposite': 'Gegenüber',
        'Past': 'Vergangenheit',
        'Plus': 'Plus',
        'Regarding': 'Bezüglich',
        'Since': 'Seit',
        'Than': 'Als',
        'Toward': 'Richtung',
        'Under': 'Unter',
        'Unlike': 'Anders als',
        'Until': 'Bis',
        'Upon': 'Auf',
        'Versus': 'Versus',
        'Via': 'Über',
        'Within': 'Innerhalb',
        
        # Long phrases
        'All rights reserved': 'Alle Rechte vorbehalten',
        'Made with': 'Gemacht mit',
        'Built with': 'Erstellt mit',
        'Powered by': 'Unterstützt von',
        'Coming Soon': 'Demnächst',
        'Under Construction': 'Im Aufbau',
        'Work in Progress': 'In Bearbeitung',
        'Stay Tuned': 'Bleiben Sie dran',
        'More to Come': 'Mehr folgt',
        'To Be Announced': 'Wird bekannt gegeben',
        'To Be Determined': 'Noch zu bestimmen',
        'Not Available': 'Nicht verfügbar',
        'Out of Stock': 'Ausverkauft',
        'In Stock': 'Auf Lager',
        'Limited Stock': 'Begrenzter Bestand',
        'Low Stock': 'Niedriger Bestand',
        'High Demand': 'Hohe Nachfrage',
        'Best Seller': 'Bestseller',
        'Most Popular': 'Am beliebtesten',
        'Customer Favorite': 'Kundenliebling',
        'Editor Choice': 'Redaktionswahl',
        'Staff Pick': 'Mitarbeiterempfehlung',
        'Limited Time': 'Begrenzte Zeit',
        'Special Offer': 'Sonderangebot',
        'Exclusive Deal': 'Exklusives Angebot',
        'Flash Sale': 'Blitzverkauf',
        'Clearance Sale': 'Räumungsverkauf',
        'End of Season': 'Saisonende',
        'Black Friday': 'Black Friday',
        'Cyber Monday': 'Cyber Monday',
        'Holiday Sale': 'Feiertagsverkauf',
        'Weekend Deal': 'Wochenendangebot',
        'Daily Deal': 'Tagesangebot',
        'Bundle Deal': 'Bundle-Angebot',
        'Buy One Get One': 'Kaufe eins, bekomme eins',
        'Free Shipping': 'Kostenloser Versand',
        'Fast Delivery': 'Schnelle Lieferung',
        'Same Day Delivery': 'Lieferung am selben Tag',
        'Next Day Delivery': 'Lieferung am nächsten Tag',
        'Express Shipping': 'Expressversand',
        'Standard Shipping': 'Standardversand',
        'International Shipping': 'Internationaler Versand',
        'Track Order': 'Bestellung verfolgen',
        'Order Status': 'Bestellstatus',
        'Order History': 'Bestellverlauf',
        'Shopping Cart': 'Warenkorb',
        'Checkout': 'Kasse',
        'Payment Method': 'Zahlungsmethode',
        'Credit Card': 'Kreditkarte',
        'Debit Card': 'Debitkarte',
        'Bank Transfer': 'Banküberweisung',
        'Cash on Delivery': 'Nachnahme',
        'Money Back Guarantee': 'Geld-zurück-Garantie',
        'Satisfaction Guarantee': 'Zufriedenheitsgarantie',
        'Quality Assurance': 'Qualitätssicherung',
        'Customer Reviews': 'Kundenbewertungen',
        'Product Reviews': 'Produktbewertungen',
        'Star Rating': 'Sternebewertung',
        'Write Review': 'Bewertung schreiben',
        'Read Reviews': 'Bewertungen lesen',
        'Ask Question': 'Frage stellen',
        'Answer Question': 'Frage beantworten',
        'Customer Questions': 'Kundenfragen',
        'Frequently Asked Questions': 'Häufig gestellte Fragen',
        'Terms and Conditions': 'Allgemeine Geschäftsbedingungen',
        'Privacy Policy': 'Datenschutzrichtlinie',
        'Cookie Policy': 'Cookie-Richtlinie',
        'Return Policy': 'Rückgaberichtlinie',
        'Refund Policy': 'Rückerstattungsrichtlinie',
        'Shipping Policy': 'Versandrichtlinie',
        'Contact Information': 'Kontaktinformationen',
        'Customer Service': 'Kundendienst',
        'Technical Support': 'Technischer Support',
        'Live Chat': 'Live-Chat',
        'Phone Support': 'Telefon-Support',
        'Email Support': 'E-Mail-Support',
        'Support Ticket': 'Support-Ticket',
        'Open Ticket': 'Ticket öffnen',
        'Close Ticket': 'Ticket schließen',
        'Ticket Status': 'Ticketstatus',
        'Priority Support': 'Prioritätssupport',
        '24/7 Support': '24/7 Support',
        'Business Hours': 'Geschäftszeiten',
        'Office Hours': 'Bürozeiten',
        'Working Hours': 'Arbeitszeiten',
        'Opening Hours': 'Öffnungszeiten',
        'Closed': 'Geschlossen',
        'Open': 'Geöffnet',
        'Available Now': 'Jetzt verfügbar',
        'Currently Unavailable': 'Derzeit nicht verfügbar',
        'Back in Stock': 'Wieder auf Lager',
        'New Arrival': 'Neuankömmling',
        'Coming Soon': 'Demnächst',
        'Pre-Order': 'Vorbestellen',
        'Reserve Now': 'Jetzt reservieren',
        'Book Now': 'Jetzt buchen',
        'Schedule Now': 'Jetzt planen',
        'Start Now': 'Jetzt starten',
        'Try Now': 'Jetzt testen',
        'Buy Now': 'Jetzt kaufen',
        'Shop Now': 'Jetzt einkaufen',
        'Order Now': 'Jetzt bestellen',
        'Download Now': 'Jetzt herunterladen',
        'Install Now': 'Jetzt installieren',
        'Update Now': 'Jetzt aktualisieren',
        'Upgrade Now': 'Jetzt upgraden',
        'Subscribe Now': 'Jetzt abonnieren',
        'Register Now': 'Jetzt registrieren',
        'Sign Up Now': 'Jetzt anmelden',
        'Join Now': 'Jetzt beitreten',
        'Apply Now': 'Jetzt bewerben',
        'Submit Now': 'Jetzt einreichen',
        'Save Now': 'Jetzt speichern',
        'Confirm Now': 'Jetzt bestätigen',
        'Accept Now': 'Jetzt akzeptieren',
        'Agree Now': 'Jetzt zustimmen',
        'Continue Shopping': 'Weiter einkaufen',
        'Keep Shopping': 'Weiter einkaufen',
        'Explore More': 'Mehr entdecken',
        'See More': 'Mehr anzeigen',
        'Load More': 'Mehr laden',
        'Show More': 'Mehr anzeigen',
        'Show Less': 'Weniger anzeigen',
        'Read More': 'Weiterlesen',
        'Learn More': 'Mehr erfahren',
        'Find Out More': 'Mehr herausfinden',
        'Discover More': 'Mehr entdecken',
        'Get Started': 'Loslegen',
        'Get Started Now': 'Jetzt loslegen',
        'Get Started Today': 'Heute loslegen',
        'Start Free Trial': 'Kostenlose Testversion starten',
        'Start Your Free Trial': 'Ihre kostenlose Testversion starten',
        'Try It Free': 'Kostenlos testen',
        'Try for Free': 'Kostenlos ausprobieren',
        'Free for 30 Days': '30 Tage kostenlos',
        'No Credit Card Required': 'Keine Kreditkarte erforderlich',
        'Cancel Anytime': 'Jederzeit kündbar',
        'No Obligation': 'Keine Verpflichtung',
        'Risk Free': 'Risikofrei',
        'Money Back': 'Geld zurück',
        'Full Refund': 'Volle Rückerstattung',
        'Partial Refund': 'Teilrückerstattung',
        'Store Credit': 'Gutschrift',
        'Gift Card': 'Geschenkkarte',
        'Promo Code': 'Aktionscode',
        'Coupon Code': 'Gutscheincode',
        'Discount Code': 'Rabattcode',
        'Apply Code': 'Code anwenden',
        'Enter Code': 'Code eingeben',
        'Redeem Code': 'Code einlösen',
        'Valid Until': 'Gültig bis',
        'Expires On': 'Läuft ab am',
        'Limited Quantity': 'Begrenzte Menge',
        'While Supplies Last': 'Solange der Vorrat reicht',
        'Subject to Availability': 'Je nach Verfügbarkeit',
        'Terms Apply': 'Es gelten Bedingungen',
        'Restrictions Apply': 'Es gelten Einschränkungen',
        'See Details': 'Details anzeigen',
        'View Details': 'Details ansehen',
        'More Details': 'Weitere Details',
        'Full Details': 'Vollständige Details',
        'Complete Details': 'Komplette Details',
        'Additional Information': 'Zusätzliche Informationen',
        'Important Information': 'Wichtige Informationen',
        'Please Note': 'Bitte beachten',
        'Attention': 'Achtung',
        'Notice': 'Hinweis',
        'Disclaimer': 'Haftungsausschluss',
        'Copyright Notice': 'Urheberrechtshinweis',
        'All Rights Reserved': 'Alle Rechte vorbehalten',
        'Trademark': 'Markenzeichen',
        'Registered Trademark': 'Eingetragenes Markenzeichen',
        'Patent Pending': 'Patent angemeldet',
        'Proprietary': 'Proprietär',
        'Confidential': 'Vertraulich',
        'Private': 'Privat',
        'Public': 'Öffentlich',
        'Internal': 'Intern',
        'External': 'Extern',
        'Incoming': 'Eingehend',
        'Outgoing': 'Ausgehend',
        'Inbound': 'Eingehend',
        'Outbound': 'Ausgehend',
        'Upload': 'Hochladen',
        'Download': 'Herunterladen',
        'Import': 'Importieren',
        'Export': 'Exportieren',
        'Backup': 'Sichern',
        'Restore': 'Wiederherstellen',
        'Sync': 'Synchronisieren',
        'Merge': 'Zusammenführen',
        'Split': 'Teilen',
        'Combine': 'Kombinieren',
        'Separate': 'Trennen',
        'Attach': 'Anhängen',
        'Detach': 'Trennen',
        'Connect': 'Verbinden',
        'Disconnect': 'Trennen',
        'Enable': 'Aktivieren',
        'Disable': 'Deaktivieren',
        'Turn On': 'Einschalten',
        'Turn Off': 'Ausschalten',
        'Switch On': 'Einschalten',
        'Switch Off': 'Ausschalten',
        'Activate': 'Aktivieren',
        'Deactivate': 'Deaktivieren',
        'Start': 'Starten',
        'Stop': 'Stoppen',
        'Begin': 'Beginnen',
        'End': 'Beenden',
        'Finish': 'Fertigstellen',
        'Complete': 'Abschließen',
        'Submit': 'Einreichen',
        'Send': 'Senden',
        'Receive': 'Empfangen',
        'Reply': 'Antworten',
        'Forward': 'Weiterleiten',
        'Share': 'Teilen',
        'Like': 'Gefällt mir',
        'Unlike': 'Gefällt mir nicht',
        'Follow': 'Folgen',
        'Unfollow': 'Entfolgen',
        'Subscribe': 'Abonnieren',
        'Unsubscribe': 'Abbestellen',
        'Bookmark': 'Lesezeichen',
        'Unbookmark': 'Lesezeichen entfernen',
        'Favorite': 'Favorit',
        'Unfavorite': 'Favorit entfernen',
        'Pin': 'Anheften',
        'Unpin': 'Lösen',
        'Lock': 'Sperren',
        'Unlock': 'Entsperren',
        'Protect': 'Schützen',
        'Unprotect': 'Schutz aufheben',
        'Secure': 'Sichern',
        'Unsecure': 'Unsicher',
        'Encrypt': 'Verschlüsseln',
        'Decrypt': 'Entschlüsseln',
        'Compress': 'Komprimieren',
        'Decompress': 'Dekomprimieren',
        'Zip': 'Zippen',
        'Unzip': 'Entpacken',
        'Pack': 'Packen',
        'Unpack': 'Auspacken',
        'Install': 'Installieren',
        'Uninstall': 'Deinstallieren',
        'Setup': 'Einrichten',
        'Configure': 'Konfigurieren',
        'Customize': 'Anpassen',
        'Personalize': 'Personalisieren',
        'Optimize': 'Optimieren',
        'Improve': 'Verbessern',
        'Enhance': 'Verbessern',
        'Upgrade': 'Aktualisieren',
        'Downgrade': 'Herunterstufen',
        'Promote': 'Befördern',
        'Demote': 'Herabstufen',
        'Elevate': 'Erhöhen',
        'Lower': 'Senken',
        'Raise': 'Erhöhen',
        'Increase': 'Erhöhen',
        'Decrease': 'Verringern',
        'Add': 'Hinzufügen',
        'Remove': 'Entfernen',
        'Insert': 'Einfügen',
        'Delete': 'Löschen',
        'Append': 'Anhängen',
        'Prepend': 'Voranstellen',
        'Replace': 'Ersetzen',
        'Substitute': 'Ersetzen',
        'Exchange': 'Austauschen',
        'Swap': 'Tauschen',
        'Trade': 'Handeln',
        'Buy': 'Kaufen',
        'Sell': 'Verkaufen',
        'Purchase': 'Erwerben',
        'Order': 'Bestellen',
        'Ship': 'Versenden',
        'Deliver': 'Liefern',
        'Return': 'Zurückgeben',
        'Refund': 'Rückerstatten',
        'Exchange': 'Umtauschen',
        'Cancel': 'Stornieren',
        'Void': 'Ungültig machen',
        'Process': 'Verarbeiten',
        'Handle': 'Bearbeiten',
        'Manage': 'Verwalten',
        'Control': 'Kontrollieren',
        'Monitor': 'Überwachen',
        'Track': 'Verfolgen',
        'Trace': 'Nachverfolgen',
        'Debug': 'Debuggen',
        'Test': 'Testen',
        'Verify': 'Überprüfen',
        'Validate': 'Validieren',
        'Check': 'Prüfen',
        'Inspect': 'Inspizieren',
        'Review': 'Überprüfen',
        'Audit': 'Prüfen',
        'Analyze': 'Analysieren',
        'Evaluate': 'Bewerten',
        'Assess': 'Beurteilen',
        'Measure': 'Messen',
        'Calculate': 'Berechnen',
        'Compute': 'Berechnen',
        'Estimate': 'Schätzen',
        'Predict': 'Vorhersagen',
        'Forecast': 'Prognostizieren',
        'Project': 'Projizieren',
        'Plan': 'Planen',
        'Schedule': 'Planen',
        'Organize': 'Organisieren',
        'Arrange': 'Arrangieren',
        'Prepare': 'Vorbereiten',
        'Ready': 'Bereit',
        'Set': 'Einstellen',
        'Adjust': 'Anpassen',
        'Calibrate': 'Kalibrieren',
        'Tune': 'Abstimmen',
        'Configure': 'Konfigurieren',
        'Program': 'Programmieren',
        'Code': 'Codieren',
        'Develop': 'Entwickeln',
        'Design': 'Entwerfen',
        'Create': 'Erstellen',
        'Build': 'Bauen',
        'Construct': 'Konstruieren',
        'Assemble': 'Zusammenbauen',
        'Manufacture': 'Herstellen',
        'Produce': 'Produzieren',
        'Generate': 'Generieren',
        'Make': 'Machen',
        'Form': 'Formen',
        'Shape': 'Gestalten',
        'Mold': 'Formen',
        'Cast': 'Gießen',
        'Forge': 'Schmieden',
        'Craft': 'Handwerken',
        'Fabricate': 'Fabrizieren',
        'Compose': 'Komponieren',
        'Write': 'Schreiben',
        'Draft': 'Entwerfen',
        'Edit': 'Bearbeiten',
        'Revise': 'Überarbeiten',
        'Proofread': 'Korrekturlesen',
        'Publish': 'Veröffentlichen',
        'Release': 'Freigeben',
        'Launch': 'Starten',
        'Deploy': 'Bereitstellen',
        'Distribute': 'Verteilen',
        'Broadcast': 'Senden',
        'Transmit': 'Übertragen',
        'Communicate': 'Kommunizieren',
        'Inform': 'Informieren',
        'Notify': 'Benachrichtigen',
        'Alert': 'Warnen',
        'Warn': 'Warnen',
        'Remind': 'Erinnern',
        'Prompt': 'Auffordern',
        'Ask': 'Fragen',
        'Request': 'Anfordern',
        'Inquire': 'Anfragen',
        'Query': 'Abfragen',
        'Search': 'Suchen',
        'Find': 'Finden',
        'Locate': 'Lokalisieren',
        'Discover': 'Entdecken',
        'Explore': 'Erkunden',
        'Browse': 'Durchsuchen',
        'Navigate': 'Navigieren',
        'Direct': 'Leiten',
        'Guide': 'Führen',
        'Lead': 'Führen',
        'Follow': 'Folgen',
        'Track': 'Verfolgen',
        'Trace': 'Nachverfolgen',
        'Monitor': 'Überwachen',
        'Watch': 'Beobachten',
        'Observe': 'Beobachten',
        'See': 'Sehen',
        'Look': 'Schauen',
        'View': 'Ansehen',
        'Display': 'Anzeigen',
        'Show': 'Zeigen',
        'Present': 'Präsentieren',
        'Demonstrate': 'Demonstrieren',
        'Illustrate': 'Illustrieren',
        'Explain': 'Erklären',
        'Describe': 'Beschreiben',
        'Define': 'Definieren',
        'Clarify': 'Klären',
        'Specify': 'Spezifizieren',
        'Detail': 'Detaillieren',
        'Elaborate': 'Ausführen',
        'Expand': 'Erweitern',
        'Extend': 'Erweitern',
        'Broaden': 'Erweitern',
        'Widen': 'Verbreitern',
        'Narrow': 'Verengen',
        'Focus': 'Fokussieren',
        'Concentrate': 'Konzentrieren',
        'Center': 'Zentrieren',
        'Align': 'Ausrichten',
        'Balance': 'Ausgleichen',
        'Stabilize': 'Stabilisieren',
        'Secure': 'Sichern',
        'Fasten': 'Befestigen',
        'Attach': 'Anbringen',
        'Fix': 'Befestigen',
        'Repair': 'Reparieren',
        'Mend': 'Ausbessern',
        'Patch': 'Flicken',
        'Update': 'Aktualisieren',
        'Refresh': 'Auffrischen',
        'Renew': 'Erneuern',
        'Restore': 'Wiederherstellen',
        'Recover': 'Wiederherstellen',
        'Retrieve': 'Abrufen',
        'Reclaim': 'Zurückfordern',
        'Salvage': 'Bergen',
        'Save': 'Speichern',
        'Preserve': 'Bewahren',
        'Maintain': 'Warten',
        'Keep': 'Behalten',
        'Hold': 'Halten',
        'Retain': 'Behalten',
        'Store': 'Speichern',
        'Archive': 'Archivieren',
        'File': 'Ablegen',
        'Organize': 'Organisieren',
        'Sort': 'Sortieren',
        'Classify': 'Klassifizieren',
        'Categorize': 'Kategorisieren',
        'Group': 'Gruppieren',
        'Cluster': 'Clustern',
        'Bundle': 'Bündeln',
        'Package': 'Verpacken',
        'Wrap': 'Einpacken',
        'Cover': 'Abdecken',
        'Protect': 'Schützen',
        'Shield': 'Abschirmen',
        'Guard': 'Bewachen',
        'Defend': 'Verteidigen',
        'Secure': 'Sichern',
        'Lock': 'Verriegeln',
        'Seal': 'Versiegeln',
        'Close': 'Schließen',
        'Shut': 'Schließen',
        'Block': 'Blockieren',
        'Prevent': 'Verhindern',
        'Stop': 'Stoppen',
        'Halt': 'Anhalten',
        'Cease': 'Aufhören',
        'Quit': 'Beenden',
        'Exit': 'Verlassen',
        'Leave': 'Verlassen',
        'Depart': 'Abreisen',
        'Go': 'Gehen',
        'Come': 'Kommen',
        'Arrive': 'Ankommen',
        'Enter': 'Eintreten',
        'Join': 'Beitreten',
        'Participate': 'Teilnehmen',
        'Engage': 'Engagieren',
        'Involve': 'Einbeziehen',
        'Include': 'Einschließen',
        'Contain': 'Enthalten',
        'Comprise': 'Umfassen',
        'Consist': 'Bestehen',
        'Compose': 'Zusammensetzen',
        'Form': 'Bilden',
        'Constitute': 'Bilden',
        'Establish': 'Etablieren',
        'Found': 'Gründen',
        'Institute': 'Einrichten',
        'Initiate': 'Initiieren',
        'Begin': 'Beginnen',
        'Commence': 'Anfangen',
        'Start': 'Starten',
        'Launch': 'Starten',
        'Open': 'Öffnen',
        'Inaugurate': 'Einweihen',
        'Introduce': 'Einführen',
        'Present': 'Vorstellen',
        'Unveil': 'Enthüllen',
        'Reveal': 'Enthüllen',
        'Disclose': 'Offenlegen',
        'Expose': 'Aufdecken',
        'Uncover': 'Aufdecken',
        'Discover': 'Entdecken',
        'Find': 'Finden',
        'Locate': 'Lokalisieren',
        'Identify': 'Identifizieren',
        'Recognize': 'Erkennen',
        'Acknowledge': 'Anerkennen',
        'Admit': 'Zugeben',
        'Confess': 'Gestehen',
        'Declare': 'Erklären',
        'Announce': 'Ankündigen',
        'Proclaim': 'Verkünden',
        'State': 'Angeben',
        'Express': 'Ausdrücken',
        'Voice': 'Äußern',
        'Speak': 'Sprechen',
        'Say': 'Sagen',
        'Tell': 'Erzählen',
        'Communicate': 'Kommunizieren',
        'Convey': 'Übermitteln',
        'Transmit': 'Übertragen',
        'Send': 'Senden',
        'Deliver': 'Liefern',
        'Provide': 'Bereitstellen',
        'Supply': 'Liefern',
        'Offer': 'Anbieten',
        'Give': 'Geben',
        'Grant': 'Gewähren',
        'Award': 'Verleihen',
        'Bestow': 'Verleihen',
        'Confer': 'Verleihen',
        'Present': 'Überreichen',
        'Hand': 'Übergeben',
        'Pass': 'Weitergeben',
        'Transfer': 'Übertragen',
        'Move': 'Bewegen',
        'Shift': 'Verschieben',
        'Change': 'Ändern',
        'Alter': 'Verändern',
        'Modify': 'Modifizieren',
        'Adjust': 'Anpassen',
        'Adapt': 'Anpassen',
        'Accommodate': 'Anpassen',
        'Fit': 'Passen',
        'Suit': 'Passen',
        'Match': 'Übereinstimmen',
        'Correspond': 'Entsprechen',
        'Relate': 'Beziehen',
        'Connect': 'Verbinden',
        'Link': 'Verknüpfen',
        'Join': 'Verbinden',
        'Unite': 'Vereinen',
        'Merge': 'Verschmelzen',
        'Combine': 'Kombinieren',
        'Blend': 'Mischen',
        'Mix': 'Mischen',
        'Integrate': 'Integrieren',
        'Incorporate': 'Einbeziehen',
        'Embed': 'Einbetten',
        'Insert': 'Einfügen',
        'Place': 'Platzieren',
        'Put': 'Setzen',
        'Position': 'Positionieren',
        'Locate': 'Lokalisieren',
        'Situate': 'Platzieren',
        'Station': 'Stationieren',
        'Post': 'Posten',
        'Deploy': 'Einsetzen',
        'Install': 'Installieren',
        'Mount': 'Montieren',
        'Affix': 'Anbringen',
        'Attach': 'Befestigen',
        'Fasten': 'Befestigen',
        'Secure': 'Sichern',
        'Fix': 'Fixieren',
        'Set': 'Setzen',
        'Establish': 'Etablieren',
        'Determine': 'Bestimmen',
        'Decide': 'Entscheiden',
        'Choose': 'Wählen',
        'Select': 'Auswählen',
        'Pick': 'Auswählen',
        'Opt': 'Entscheiden',
        'Prefer': 'Bevorzugen',
        'Favor': 'Bevorzugen',
        'Like': 'Mögen',
        'Love': 'Lieben',
        'Enjoy': 'Genießen',
        'Appreciate': 'Schätzen',
        'Value': 'Wertschätzen',
        'Respect': 'Respektieren',
        'Honor': 'Ehren',
        'Admire': 'Bewundern',
        'Praise': 'Loben',
        'Commend': 'Loben',
        'Applaud': 'Applaudieren',
        'Congratulate': 'Gratulieren',
        'Celebrate': 'Feiern',
        'Commemorate': 'Gedenken',
        'Remember': 'Erinnern',
        'Recall': 'Zurückrufen',
        'Recollect': 'Sich erinnern',
        'Remind': 'Erinnern',
        'Forget': 'Vergessen',
        'Overlook': 'Übersehen',
        'Ignore': 'Ignorieren',
        'Neglect': 'Vernachlässigen',
        'Disregard': 'Missachten',
        'Dismiss': 'Abweisen',
        'Reject': 'Ablehnen',
        'Refuse': 'Verweigern',
        'Decline': 'Ablehnen',
        'Deny': 'Verweigern',
        'Oppose': 'Widersetzen',
        'Resist': 'Widerstehen',
        'Fight': 'Kämpfen',
        'Combat': 'Bekämpfen',
        'Battle': 'Kämpfen',
        'Struggle': 'Kämpfen',
        'Compete': 'Konkurrieren',
        'Contest': 'Wettstreiten',
        'Challenge': 'Herausfordern',
        'Confront': 'Konfrontieren',
        'Face': 'Gegenüberstehen',
        'Encounter': 'Begegnen',
        'Meet': 'Treffen',
        'Greet': 'Begrüßen',
        'Welcome': 'Willkommen',
        'Receive': 'Empfangen',
        'Accept': 'Akzeptieren',
        'Take': 'Nehmen',
        'Get': 'Bekommen',
        'Obtain': 'Erhalten',
        'Acquire': 'Erwerben',
        'Gain': 'Gewinnen',
        'Win': 'Gewinnen',
        'Earn': 'Verdienen',
        'Achieve': 'Erreichen',
        'Accomplish': 'Vollbringen',
        'Complete': 'Abschließen',
        'Finish': 'Beenden',
        'Conclude': 'Abschließen',
        'Terminate': 'Beenden',
        'End': 'Enden',
        'Stop': 'Stoppen',
        'Cease': 'Aufhören',
        'Halt': 'Anhalten',
        'Pause': 'Pausieren',
        'Suspend': 'Aussetzen',
        'Interrupt': 'Unterbrechen',
        'Break': 'Brechen',
        'Disrupt': 'Stören',
        'Disturb': 'Stören',
        'Interfere': 'Einmischen',
        'Intervene': 'Eingreifen',
        'Mediate': 'Vermitteln',
        'Arbitrate': 'Schlichten',
        'Negotiate': 'Verhandeln',
        'Discuss': 'Diskutieren',
        'Talk': 'Sprechen',
        'Converse': 'Unterhalten',
        'Chat': 'Plaudern',
        'Communicate': 'Kommunizieren',
        'Correspond': 'Korrespondieren',
        'Write': 'Schreiben',
        'Compose': 'Verfassen',
        'Draft': 'Entwerfen',
        'Create': 'Erstellen',
        'Produce': 'Produzieren',
        'Generate': 'Erzeugen',
        'Make': 'Machen',
        'Build': 'Bauen',
        'Construct': 'Konstruieren',
        'Develop': 'Entwickeln',
        'Design': 'Entwerfen',
        'Plan': 'Planen',
        'Prepare': 'Vorbereiten',
        'Arrange': 'Arrangieren',
        'Organize': 'Organisieren',
        'Structure': 'Strukturieren',
        'Format': 'Formatieren',
        'Style': 'Gestalten',
        'Customize': 'Anpassen',
        'Personalize': 'Personalisieren',
        'Tailor': 'Maßschneidern',
        'Adapt': 'Anpassen',
        'Modify': 'Modifizieren',
        'Change': 'Ändern',
        'Transform': 'Transformieren',
        'Convert': 'Konvertieren',
        'Translate': 'Übersetzen',
        'Interpret': 'Interpretieren',
        'Explain': 'Erklären',
        'Clarify': 'Klären',
        'Simplify': 'Vereinfachen',
        'Complicate': 'Verkomplizieren',
        'Confuse': 'Verwirren',
        'Mislead': 'Irreführen',
        'Deceive': 'Täuschen',
        'Trick': 'Austricksen',
        'Fool': 'Täuschen',
        'Cheat': 'Betrügen',
        'Steal': 'Stehlen',
        'Rob': 'Rauben',
        'Take': 'Nehmen',
        'Seize': 'Ergreifen',
        'Capture': 'Erfassen',
        'Catch': 'Fangen',
        'Trap': 'Fangen',
        'Snare': 'Fangen',
        'Hunt': 'Jagen',
        'Chase': 'Jagen',
        'Pursue': 'Verfolgen',
        'Follow': 'Folgen',
        'Trail': 'Verfolgen',
        'Track': 'Verfolgen',
        'Trace': 'Nachvollziehen',
        'Find': 'Finden',
        'Discover': 'Entdecken',
        'Uncover': 'Aufdecken',
        'Reveal': 'Enthüllen',
        'Expose': 'Bloßstellen',
        'Show': 'Zeigen',
        'Display': 'Anzeigen',
        'Exhibit': 'Ausstellen',
        'Present': 'Präsentieren',
        'Demonstrate': 'Demonstrieren',
        'Prove': 'Beweisen',
        'Verify': 'Verifizieren',
        'Confirm': 'Bestätigen',
        'Validate': 'Validieren',
        'Authenticate': 'Authentifizieren',
        'Certify': 'Zertifizieren',
        'Guarantee': 'Garantieren',
        'Warrant': 'Gewährleisten',
        'Ensure': 'Sicherstellen',
        'Assure': 'Versichern',
        'Promise': 'Versprechen',
        'Pledge': 'Geloben',
        'Vow': 'Schwören',
        'Swear': 'Schwören',
        'Commit': 'Verpflichten',
        'Dedicate': 'Widmen',
        'Devote': 'Widmen',
        'Contribute': 'Beitragen',
        'Donate': 'Spenden',
        'Give': 'Geben',
        'Offer': 'Anbieten',
        'Provide': 'Bereitstellen',
        'Supply': 'Liefern',
        'Deliver': 'Liefern',
        'Ship': 'Versenden',
        'Send': 'Senden',
        'Mail': 'Versenden',
        'Post': 'Posten',
        'Dispatch': 'Versenden',
        'Forward': 'Weiterleiten',
        'Transfer': 'Übertragen',
        'Transport': 'Transportieren',
        'Carry': 'Tragen',
        'Bring': 'Bringen',
        'Take': 'Nehmen',
        'Move': 'Bewegen',
        'Shift': 'Verschieben',
        'Relocate': 'Umziehen',
        'Migrate': 'Migrieren',
        'Travel': 'Reisen',
        'Journey': 'Reisen',
        'Tour': 'Touren',
        'Visit': 'Besuchen',
        'Explore': 'Erkunden',
        'Wander': 'Wandern',
        'Roam': 'Umherstreifen',
        'Walk': 'Gehen',
        'Run': 'Laufen',
        'Jump': 'Springen',
        'Leap': 'Springen',
        'Hop': 'Hüpfen',
        'Skip': 'Überspringen',
        'Dance': 'Tanzen',
        'Sing': 'Singen',
        'Play': 'Spielen',
        'Perform': 'Aufführen',
        'Act': 'Handeln',
        'Behave': 'Verhalten',
        'React': 'Reagieren',
        'Respond': 'Antworten',
        'Answer': 'Antworten',
        'Reply': 'Antworten',
        'Retort': 'Erwidern',
        'Counter': 'Kontern',
        'Oppose': 'Opponieren',
        'Contradict': 'Widersprechen',
        'Dispute': 'Bestreiten',
        'Argue': 'Argumentieren',
        'Debate': 'Debattieren',
        'Discuss': 'Diskutieren',
        'Converse': 'Unterhalten',
        'Talk': 'Reden',
        'Speak': 'Sprechen',
        'Say': 'Sagen',
        'Tell': 'Erzählen',
        'Inform': 'Informieren',
        'Notify': 'Benachrichtigen',
        'Advise': 'Beraten',
        'Counsel': 'Beraten',
        'Guide': 'Führen',
        'Direct': 'Leiten',
        'Instruct': 'Anweisen',
        'Teach': 'Lehren',
        'Educate': 'Bilden',
        'Train': 'Trainieren',
        'Coach': 'Coachen',
        'Mentor': 'Betreuen',
        'Tutor': 'Nachhilfe geben',
        'Learn': 'Lernen',
        'Study': 'Studieren',
        'Research': 'Forschen',
        'Investigate': 'Untersuchen',
        'Examine': 'Untersuchen',
        'Inspect': 'Inspizieren',
        'Scrutinize': 'Prüfen',
        'Analyze': 'Analysieren',
        'Evaluate': 'Bewerten',
        'Assess': 'Beurteilen',
        'Judge': 'Beurteilen',
        'Rate': 'Bewerten',
        'Score': 'Bewerten',
        'Grade': 'Benoten',
        'Rank': 'Einstufen',
        'Classify': 'Klassifizieren',
        'Categorize': 'Kategorisieren',
        'Sort': 'Sortieren',
        'Organize': 'Organisieren',
        'Arrange': 'Anordnen',
        'Order': 'Ordnen',
        'Sequence': 'Sequenzieren',
        'List': 'Auflisten',
        'Enumerate': 'Aufzählen',
        'Count': 'Zählen',
        'Number': 'Nummerieren',
        'Calculate': 'Berechnen',
        'Compute': 'Berechnen',
        'Estimate': 'Schätzen',
        'Approximate': 'Annähern',
        'Round': 'Runden',
        'Truncate': 'Abschneiden',
        'Limit': 'Begrenzen',
        'Restrict': 'Einschränken',
        'Constrain': 'Beschränken',
        'Confine': 'Begrenzen',
        'Bound': 'Begrenzen',
        'Contain': 'Enthalten',
        'Hold': 'Halten',
        'Keep': 'Behalten',
        'Maintain': 'Aufrechterhalten',
        'Preserve': 'Bewahren',
        'Protect': 'Schützen',
        'Guard': 'Bewachen',
        'Defend': 'Verteidigen',
        'Shield': 'Abschirmen',
        'Cover': 'Abdecken',
        'Wrap': 'Einwickeln',
        'Enclose': 'Einschließen',
        'Surround': 'Umgeben',
        'Encircle': 'Umkreisen',
        'Ring': 'Umringen',
        'Circle': 'Kreisen',
        'Loop': 'Schleifen',
        'Cycle': 'Zyklus',
        'Repeat': 'Wiederholen',
        'Recur': 'Wiederkehren',
        'Return': 'Zurückkehren',
        'Come Back': 'Zurückkommen',
        'Go Back': 'Zurückgehen',
        'Retreat': 'Zurückziehen',
        'Withdraw': 'Zurückziehen',
        'Pull Back': 'Zurückziehen',
        'Draw Back': 'Zurückziehen',
        'Step Back': 'Zurücktreten',
        'Move Back': 'Zurückbewegen',
        'Push Back': 'Zurückdrängen',
        'Hold Back': 'Zurückhalten',
        'Keep Back': 'Zurückhalten',
        'Stay Back': 'Zurückbleiben',
        'Remain': 'Bleiben',
        'Stay': 'Bleiben',
        'Continue': 'Fortsetzen',
        'Persist': 'Beharren',
        'Persevere': 'Durchhalten',
        'Endure': 'Ertragen',
        'Last': 'Dauern',
        'Survive': 'Überleben',
        'Live': 'Leben',
        'Exist': 'Existieren',
        'Be': 'Sein',
        'Become': 'Werden',
        'Grow': 'Wachsen',
        'Develop': 'Entwickeln',
        'Evolve': 'Entwickeln',
        'Progress': 'Fortschreiten',
        'Advance': 'Voranschreiten',
        'Proceed': 'Fortfahren',
        'Continue': 'Weitermachen',
        'Carry On': 'Weitermachen',
        'Go On': 'Weitergehen',
        'Keep Going': 'Weitermachen',
        'Move Forward': 'Vorwärtsgehen',
        'Push Forward': 'Vorwärtsdrängen',
        'Press On': 'Weitermachen',
        'March On': 'Weitermarschieren',
        'Walk On': 'Weitergehen',
        'Step Forward': 'Vortreten',
        'Come Forward': 'Vortreten',
        'Bring Forward': 'Vorbringen',
        'Put Forward': 'Vorbringen',
        'Set Forward': 'Vorbringen',
        'Lay Out': 'Auslegen',
        'Set Out': 'Darlegen',
        'Start Out': 'Anfangen',
        'Begin': 'Beginnen',
        'Commence': 'Anfangen',
        'Initiate': 'Initiieren',
        'Launch': 'Starten',
        'Kick Off': 'Anstoßen',
        'Get Going': 'Loslegen',
        'Get Started': 'Anfangen',
        'Set In Motion': 'In Gang setzen',
        'Put In Motion': 'In Bewegung setzen',
        'Set Up': 'Einrichten',
        'Put Up': 'Aufstellen',
        'Build Up': 'Aufbauen',
        'Work Up': 'Ausarbeiten',
        'Draw Up': 'Aufstellen',
        'Write Up': 'Aufschreiben',
        'Type Up': 'Abtippen',
        'Print Out': 'Ausdrucken',
        'Hand Out': 'Austeilen',
        'Give Out': 'Ausgeben',
        'Send Out': 'Aussenden',
        'Put Out': 'Herausgeben',
        'Bring Out': 'Herausbringen',
        'Come Out': 'Herauskommen',
        'Get Out': 'Herauskommen',
        'Go Out': 'Ausgehen',
        'Walk Out': 'Hinausgehen',
        'Step Out': 'Hinaustreten',
        'Move Out': 'Ausziehen',
        'Pull Out': 'Herausziehen',
        'Take Out': 'Herausnehmen',
        'Bring In': 'Hereinbringen',
        'Come In': 'Hereinkommen',
        'Get In': 'Hineinkommen',
        'Go In': 'Hineingehen',
        'Walk In': 'Hineingehen',
        'Step In': 'Eintreten',
        'Move In': 'Einziehen',
        'Pull In': 'Hineinziehen',
        'Take In': 'Aufnehmen',
        'Let In': 'Hereinlassen',
        'Allow In': 'Hereinlassen',
        'Bring About': 'Herbeiführen',
        'Come About': 'Zustande kommen',
        'Go About': 'Angehen',
        'Set About': 'Sich anschicken',
        'Think About': 'Nachdenken über',
        'Talk About': 'Sprechen über',
        'Write About': 'Schreiben über',
        'Read About': 'Lesen über',
        'Learn About': 'Lernen über',
        'Know About': 'Wissen über',
        'Care About': 'Sich kümmern um',
        'Worry About': 'Sich sorgen um',
        'Think Of': 'Denken an',
        'Dream Of': 'Träumen von',
        'Speak Of': 'Sprechen von',
        'Talk Of': 'Reden von',
        'Think Through': 'Durchdenken',
        'Work Through': 'Durcharbeiten',
        'Go Through': 'Durchgehen',
        'Get Through': 'Durchkommen',
        'Come Through': 'Durchkommen',
        'Pull Through': 'Durchkommen',
        'See Through': 'Durchschauen',
        'Look Through': 'Durchsehen',
        'Read Through': 'Durchlesen',
        'Run Through': 'Durchlaufen',
        'Walk Through': 'Durchgehen',
        'Talk Through': 'Durchsprechen',
        'Think Over': 'Überdenken',
        'Look Over': 'Übersehen',
        'Go Over': 'Durchgehen',
        'Run Over': 'Überfahren',
        'Take Over': 'Übernehmen',
        'Hand Over': 'Übergeben',
        'Turn Over': 'Umdrehen',
        'Roll Over': 'Überrollen',
        'Come Over': 'Herüberkommen',
        'Get Over': 'Überwinden',
        'Look Up': 'Nachschlagen',
        'Pick Up': 'Aufheben',
        'Take Up': 'Aufnehmen',
        'Give Up': 'Aufgeben',
        'Set Up': 'Einrichten',
        'Put Up': 'Aufstellen',
        'Hold Up': 'Hochhalten',
        'Keep Up': 'Mithalten',
        'Catch Up': 'Aufholen',
        'Make Up': 'Wiedergutmachen',
        'Break Up': 'Auflösen',
        'Split Up': 'Aufteilen',
        'Cut Up': 'Zerschneiden',
        'Tear Up': 'Zerreißen',
        'Blow Up': 'Explodieren',
        'Build Up': 'Aufbauen',
        'Work Up': 'Ausarbeiten',
        'Draw Up': 'Aufstellen',
        'Write Up': 'Aufschreiben',
        'Type Up': 'Abtippen',
        'Look Down': 'Hinunterschauen',
        'Put Down': 'Ablegen',
        'Set Down': 'Niederlegen',
        'Lay Down': 'Hinlegen',
        'Sit Down': 'Hinsetzen',
        'Lie Down': 'Hinlegen',
        'Fall Down': 'Hinfallen',
        'Break Down': 'Zusammenbrechen',
        'Shut Down': 'Herunterfahren',
        'Close Down': 'Schließen',
        'Turn Down': 'Ablehnen',
        'Slow Down': 'Verlangsamen',
        'Calm Down': 'Beruhigen',
        'Cool Down': 'Abkühlen',
        'Settle Down': 'Sich niederlassen',
        'Write Down': 'Aufschreiben',
        'Note Down': 'Notieren',
        'Jot Down': 'Notieren',
        'Take Down': 'Aufschreiben',
        'Put Away': 'Wegräumen',
        'Give Away': 'Verschenken',
        'Throw Away': 'Wegwerfen',
        'Take Away': 'Wegnehmen',
        'Go Away': 'Weggehen',
        'Get Away': 'Wegkommen',
        'Run Away': 'Weglaufen',
        'Walk Away': 'Weggehen',
        'Turn Away': 'Abwenden',
        'Look Away': 'Wegschauen',
        'Stay Away': 'Fernbleiben',
        'Keep Away': 'Fernhalten',
        'Put Off': 'Verschieben',
        'Take Off': 'Abnehmen',
        'Turn Off': 'Ausschalten',
        'Switch Off': 'Ausschalten',
        'Go Off': 'Losgehen',
        'Set Off': 'Aufbrechen',
        'Show Off': 'Angeben',
        'Pay Off': 'Auszahlen',
        'Lay Off': 'Entlassen',
        'Call Off': 'Absagen',
        'Break Off': 'Abbrechen',
        'Cut Off': 'Abschneiden',
        'Put On': 'Anziehen',
        'Take On': 'Übernehmen',
        'Turn On': 'Einschalten',
        'Switch On': 'Einschalten',
        'Go On': 'Weitergehen',
        'Carry On': 'Weitermachen',
        'Move On': 'Weitergehen',
        'Pass On': 'Weitergeben',
        'Hold On': 'Festhalten',
        'Hang On': 'Durchhalten',
        'Come Together': 'Zusammenkommen',
        'Get Together': 'Sich treffen',
        'Put Together': 'Zusammensetzen',
        'Bring Together': 'Zusammenbringen',
        'Work Together': 'Zusammenarbeiten',
        'Stay Together': 'Zusammenbleiben',
        'Stick Together': 'Zusammenhalten',
        'Hold Together': 'Zusammenhalten',
        'Come Apart': 'Auseinanderfallen',
        'Fall Apart': 'Auseinanderfallen',
        'Take Apart': 'Auseinandernehmen',
        'Pull Apart': 'Auseinanderziehen',
        'Tear Apart': 'Zerreißen',
        'Break Apart': 'Auseinanderbrechen',
        'Drift Apart': 'Auseinanderdriften',
        'Grow Apart': 'Sich auseinanderleben',
        'Stand By': 'Bereitstehen',
        'Go By': 'Vorbeigehen',
        'Pass By': 'Vorbeigehen',
        'Stop By': 'Vorbeikommen',
        'Drop By': 'Vorbeischauen',
        'Come By': 'Vorbeikommen',
        'Get By': 'Durchkommen',
        'Live By': 'Leben nach',
        'Abide By': 'Sich halten an',
        'Stand For': 'Stehen für',
        'Go For': 'Sich entscheiden für',
        'Look For': 'Suchen nach',
        'Wait For': 'Warten auf',
        'Hope For': 'Hoffen auf',
        'Ask For': 'Bitten um',
        'Call For': 'Aufrufen zu',
        'Care For': 'Sorgen für',
        'Provide For': 'Sorgen für',
        'Allow For': 'Berücksichtigen',
        'Account For': 'Erklären',
        'Stand Against': 'Sich stellen gegen',
        'Go Against': 'Verstoßen gegen',
        'Turn Against': 'Sich wenden gegen',
        'Fight Against': 'Kämpfen gegen',
        'Protect Against': 'Schützen vor',
        'Guard Against': 'Sich hüten vor',
        'Warn Against': 'Warnen vor',
        'Advise Against': 'Abraten von',
        'Decide Against': 'Sich entscheiden gegen',
        'Vote Against': 'Stimmen gegen',
        'Come Across': 'Stoßen auf',
        'Run Across': 'Zufällig treffen',
        'Get Across': 'Rüberbringen',
        'Put Across': 'Vermitteln',
        'Come Along': 'Mitkommen',
        'Get Along': 'Auskommen',
        'Go Along': 'Mitgehen',
        'Move Along': 'Weitergehen',
        'Bring Along': 'Mitbringen',
        'Take Along': 'Mitnehmen',
        'Come Around': 'Vorbeikommen',
        'Get Around': 'Herumkommen',
        'Go Around': 'Herumgehen',
        'Turn Around': 'Umdrehen',
        'Look Around': 'Sich umsehen',
        'Shop Around': 'Sich umsehen',
        'Come Before': 'Kommen vor',
        'Go Before': 'Vorangehen',
        'Stand Before': 'Stehen vor',
        'Appear Before': 'Erscheinen vor',
        'Come Between': 'Dazwischenkommen',
        'Get Between': 'Dazwischenkommen',
        'Stand Between': 'Stehen zwischen',
        'Choose Between': 'Wählen zwischen',
        'Come From': 'Kommen aus',
        'Get From': 'Bekommen von',
        'Hear From': 'Hören von',
        'Learn From': 'Lernen von',
        'Benefit From': 'Profitieren von',
        'Suffer From': 'Leiden unter',
        'Recover From': 'Sich erholen von',
        'Come Into': 'Kommen in',
        'Get Into': 'Hineinkommen',
        'Go Into': 'Hineingehen',
        'Look Into': 'Untersuchen',
        'Run Into': 'Hineinlaufen',
        'Bump Into': 'Zufällig treffen',
        'Come With': 'Kommen mit',
        'Go With': 'Passen zu',
        'Work With': 'Arbeiten mit',
        'Deal With': 'Umgehen mit',
        'Cope With': 'Bewältigen',
        'Live With': 'Leben mit',
        'Come Without': 'Kommen ohne',
        'Go Without': 'Verzichten auf',
        'Do Without': 'Auskommen ohne',
        'Live Without': 'Leben ohne'
    }

def translate_text(text):
    """Main translation function"""
    if should_preserve(text):
        return text
    
    translations = get_comprehensive_translations()
    
    # Check for exact match
    if text in translations:
        return translations[text]
    
    # Check for case-insensitive match
    for eng, ger in translations.items():
        if eng.lower() == text.lower():
            return ger
    
    # For longer phrases, try to translate by replacing known phrases
    result = text
    for eng, ger in sorted(translations.items(), key=lambda x: len(x[0]), reverse=True):
        # Replace while preserving special content
        if eng in result:
            result = result.replace(eng, ger)
    
    return result

def translate_json_value(value):
    """Recursively translate JSON values"""
    if isinstance(value, str):
        return translate_text(value)
    elif isinstance(value, list):
        return [translate_json_value(item) for item in value]
    elif isinstance(value, dict):
        return {k: translate_json_value(v) for k, v in value.items()}
    else:
        return value

def main():
    print("Loading de.json for complete translation...")
    
    with open('public/locales/de.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    print("Translating all English content to German...")
    translated_data = translate_json_value(data)
    
    print("Saving fully translated de.json...")
    with open('public/locales/de.json', 'w', encoding='utf-8') as f:
        json.dump(translated_data, f, ensure_ascii=False, indent=2)
    
    print("Translation completed!")
    
    # Validate JSON
    with open('public/locales/de.json', 'r', encoding='utf-8') as f:
        json.load(f)
    print("JSON validation successful!")

if __name__ == "__main__":
    main()
